### ISSUE TITLE
In editor, quoted code should have sandboxed highlighting

### ISSUE THREAD

**Issue by boamaod** [jamiemcg/Remarkable#107]
Otherwise, what happens, is that if the code quoted is a diff of HTML/MarkDown file or some other fragmented file without proper tag start/end pairs, then all the highlighting is messed up in editor.

![remarkable_highlight](https://cloud.githubusercontent.com/assets/736994/22400380/a13512ec-e5bb-11e6-946c-2ce261461354.png)

**Comment by jamiemcg** [comment]
This is the default behavior of GtkSourceView which Remarkable used. It would have to be fixed upstream.
