### ISSUE TITLE
GitHub markdown for lists displays incorrectly

### ISSUE THREAD

**Issue by lhriley** [jamiemcg/Remarkable#108]
I noticed that when creating a list, the preview in Remarkable when using the `Github (Default)` style does not match the [Github Markdown Styleguide](https://guides.github.com/features/mastering-markdown/). This applies to ordered, unordered, and mixed order lists.

**Remarkable version 1.87**
**Linux Mint 18.1**

### Example 1:

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this

### Example 2:

1. line 1
2. line 2
   1. line 2.1
3. line 3
   * line 3.*

***

### Example 1:

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
- Like this
- And this

### Example 2:

- line 1
- line 2
- line 2.1
- line 3
- line 3.*

***

### Example 1:

```
- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this
```

### Example 2:

```
1. line 1
2. line 2
   1. line 2.1
3. line 3
   * line 3.*
```

**Comment by vphantom** [comment]
I played with this bug, and it appears that Remarkable expects 4 spaces per indent level, whereas GitHub only needs 2 spaces.

**Comment by vphantom** [comment]
I suspect this is actually an issue for [python-markdown](https://github.com/waylan/Python-Markdown) but I'm not familiar enough with how Remarkable is packaged, or Python in general, to be sure this is what's being used to render it to HTML.
