### ISSUE TITLE
Am I wrong or Remarkable just doesn't support to-do list at the moment?

### ISSUE THREAD

**Issue by huyvohcmc** [jamiemcg/Remarkable#112]
Am I wrong or Remarkable just doesn't support to-do list at the moment?

![image](https://cloud.githubusercontent.com/assets/17645203/22875801/3225349e-f200-11e6-9615-0f67f02c7aa2.png)

Oh, I'm using Remarkable 1.87 btw...

**Comment by tleb** [comment]
From what I've found, Remarkable uses [this package](https://pypi.python.org/pypi/Markdown) for Markdown, which [doesn't seem to include anything for checkboxes](https://pythonhosted.org/Markdown/extensions/index.html).

[markdown-checkbox](https://github.com/FND/markdown-checklist) should be the answer but [we can't build Remarkable from source](https://github.com/jamiemcg/Remarkable/issues/67#issuecomment-254041520), so we can't solve it ourselves. 😐
