### ISSUE TITLE
Syntax highlighting breaks if less symbol (>) is used in math environment

### ISSUE THREAD

**Issue by romanovzky** [jamiemcg/Remarkable#113]
In Linux (ubuntu and arch), Remarkable v.1.87. The code should ignore bindings for < if used inside Math environment.

![screenshot](http://i.imgur.com/zZN4sTW.png)

**Comment by romanovzky** [comment]
Would it be possible to have this merged? For some reason, my ticket was closed without any feedback...

**Comment by 1one-w01f** [comment]
@jamiemcg Would you consider adding a separate language spec file into Remarkable?

In fact, I think both Remarkable the app and the extended Markdowns have outgrown the original markdown language spec that GtkSourceView ships. 

Remarkable can certainly consider using its own language spec file, and call  `self.lang_manager.set_search_path()` before `self.lang_manager.get_language()`.
