### ISSUE TITLE
Copy with keyboard (CTRL+C) not working in preview

### ISSUE THREAD

**Issue by carlos22** [jamiemcg/Remarkable#118]
Coping of text from the preview (webkit) view is not possible with CTRL+C only via context menu.

**Comment by carlos22** [comment]
There seems to be a PR #116

**Comment by carlos22** [comment]
Is it fixed? I don't see any commits or PR merges?

**Comment by SupermeReturns** [comment]
I am encountering the same problem on Ubuntu with version 1.87, is it solved ？@carlos 22

**Comment by SupermeReturns** [comment]
@jamiemcg @carlos22
