### ISSUE TITLE
Make remarkable WYSIWYG

### ISSUE THREAD

**Issue by parrenin** [jamiemcg/Remarkable#120]
I like remarkable in general but I dislike the dual view.
I would like a pure WYSIWYG mode, where you don't see the editor.

**Comment by tleb** [comment]
If you need a WYSIWYG, don't use a Markdown editor...

**Comment by parrenin** [comment]
Hm, I am not sure I see your point here.
You may want a WYSIWYG editor but with the Markdown shortcuts.
A bit like what Lyx is to Latex.
Actually there are WYSIWYG Markdown editors, the problem being that they are non-free.
