### ISSUE TITLE
Defect: Arabic numbers aren't generated in counted lists, only roman numbers.

### ISSUE THREAD

**Issue by scherrey** [jamiemcg/Remarkable#126]
Running Remarkable build 1.87 for Debian under Kubuntu 14.04 which was downloaded from the website.

Given:

```
# Where are my arabic numbers?

Only get roman numbers:

1. First
2. Second
3. Third
```

The arabic numbers 1,2,3 never show up in the output. I only get i, ii, iii.

**Comment by scherrey** [comment]
Remarkably (heh), I spent a few hours last night trying out other markdown editors - gave up. After waking up and starting the app again, now I ONLY get arabic numerals and can't get roman ones. I expect this means that there's some 3rd party dependency that got changed during my attempts last night that is the real culprit. Any ideas what that might be?

**Comment by jamiemcg** [comment]
Markdown parsing in Remarkable is handled by [Python Markdown](https://github.com/waylan/Python-Markdown). Could be something there
