### ISSUE TITLE
underscore in table

### ISSUE THREAD

**Issue by mmahmoudian** [jamiemcg/Remarkable#129]
In editor panel if we have underscore "_" in two different columns, everything in between these two will become italic. This should at best happen only when two "_" are between two "|" (basically when both "_" are in one column).

To see what I mean, simply try md source of the following:

| A_B | A_C |
|----:|----:|
| X_Y | W_X |

**Comment by jamiemcg** [comment]
Remarkable used [Python Markdown](https://github.com/waylan/Python-Markdown) to handle markdown parsing. This is an upstream bug.
