### ISSUE TITLE
can't install .deb on testing

### ISSUE THREAD

**Issue by ilrico** [jamiemcg/Remarkable#136]
dpki -i remarkable_package.deb returns:

_dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:  
  Package gir1.2-gtksource-3.0 is not installed.  
 remarkable depends on python3-markdown; however:  
  Package python3-markdown is not installed.
 remarkable depends on python3-bs4; however:
  Package python3-bs4 is not installed.
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed._

**Comment by jamiemcg** [comment]
**dpkg** doesn't install dependencies for you. Install the required dependencies (listed in the error message) or use something like [gebi](https://apps.ubuntu.com/cat/applications/precise/gdebi/) to install the required packages for you.

**Comment by ilrico** [comment]
Yes problem comes from broken dependencies on what Remarkable needs, not from Remarkable packet itself.
