### ISSUE TITLE
Column alignment for tables not rendered in preview

### ISSUE THREAD

**Issue by knzudgt** [jamiemcg/Remarkable#139]
Column alignment with one or two colons is not rendered in preview.
Is this a markdown extra feature missing in Remarkable or there are other reasons why columns are always left aligned in preview?

| Item     | Value | Qty   |
| :------- | ----: | :---: |
| Computer | $1200 |  12    |
| Phone    | $120   |  37   |
| Headphone     | $60   |  234  |

**Comment by Jolt2bolt** [comment]
I got the same problem and I  confirm that still it's there!

**Comment by hybcloud** [comment]
I got the same problem and I confirm that still it's there, too.
