### ISSUE TITLE
Add tabs support

### ISSUE THREAD

**Issue by firetrot** [jamiemcg/Remarkable#154]
Hi!
It would be so great if you add tabs to your app (like gedit).
![image](https://cloud.githubusercontent.com/assets/2574574/25473701/1fa14a84-2b39-11e7-9f61-09d25ad16b94.png)

Now i should open several apps instances and Alt-Tab between them. With tabs it'll be convenient.
Remarkable is awesome, thanks for your job!

**Comment by Larivact** [comment]
Duplicate of  #24.

**Comment by firetrot** [comment]
Delete the thread permanently, please.

**Comment by mbloms** [comment]
@firetrot that's not even possible on github. Think before you post.
