### ISSUE TITLE
save documents automatically or recover the  document

### ISSUE THREAD

**Issue by rookiebird** [jamiemcg/Remarkable#155]
Thanks to such a software that makes my job easier and easier.But I wonder if there is a function that can save the documents automatically or recover from an error which may be cause by an electricity black-out.Last time my computer suddenly shut down and all my work was lost...

**Comment by eosoba** [comment]
Oh god, yes please, an auto save feature. I just lost a day's worth of work :(

**Comment by LC43** [comment]
+1 for this too. It broken down with seg fault and lost some edits.
