### ISSUE TITLE
[Feature Request]Auto-save

### ISSUE THREAD

**Issue by sujunhao** [jamiemcg/Remarkable#158]
Remarkable will more useful if it can auto-save files

**Comment by BennyThink** [comment]
This is quite similar with issue #155, I believe this would be an important and reliable function.
Hopefully we'll see it soon.

**Comment by felix91gr** [comment]
Is this being worked on? Is there a bug tracking ticket for this? I need this to be implemented. Please.
I have a bug I can't figure out with X-Server and sometimes my computer's GUI goes caput. Even having a timed autosave, to be triggered every minute or so, would be fantastic.
