### ISSUE TITLE
Markdown highlighting in Editor Pane

### ISSUE THREAD

**Issue by Paviluf** [jamiemcg/Remarkable#16]
Hello,

It will be great if the markdown can be highlighted like this (left side) :

![](https://cloud.githubusercontent.com/assets/378023/10013086/24cad23e-6149-11e5-90e6-663009210218.png)

Thanks !

**Comment by jamiemcg** [comment]
This feature is added in version 1.87

[Remarkable homepage)(http://remarkableapp.github.io/linux.html)

**Comment by Paviluf** [comment]
That's awesome ! Thank you very much !
