### ISSUE TITLE
Footnotes not rendered

### ISSUE THREAD

**Issue by emilhe** [jamiemcg/Remarkable#163]
I just installed remarkable (from the .deb package on the official site), but it seems that footnotes are not working. Here is my MWE:

![mwe](https://cloud.githubusercontent.com/assets/1623542/26282952/4f5bf746-3e1d-11e7-8d2d-bf27c54e324e.jpg)

Have i done something wrong or is it a bug?

**Comment by Matthias84** [comment]
You are using an wrong syntax [for footnotes](https://pythonhosted.org/Markdown/extensions/footnotes.html). It works like this and is rendered in preview:

>Footnotes[^1] have a label and the footnote's content.
>[^1]: This is a footnote content.
