### ISSUE TITLE
Mathematical Formula error in Ubuntu16.04

### ISSUE THREAD

**Issue by Jeromezp** [jamiemcg/Remarkable#164]
I just installed remarkable (from the .deb package on the official site),but it seems that Mathematical Formula are not working.
![error](https://cloud.githubusercontent.com/assets/10430564/26285952/5c1e9f28-3e8c-11e7-95ae-b09836d3299e.png)

**Comment by emilhe** [comment]
Duplicate of #160. See the original issue for a quick fix.
