### ISSUE TITLE
Support export to PDF/HTML from terminal

### ISSUE THREAD

**Issue by dartie** [jamiemcg/Remarkable#168]
The export to PDF/HTML should be possible via command line 
Parameters should be:
- input file
- output format
- css style [optional parameter]

Example:
``` 
remarkable -o pdf text.md 
```
``` 
remarkable -o hrml text.md 
```
``` 
remarkable -o pdf text.md -css "dark"
```
``` 
remarkable -o hrml text.md -css "dark"
```

**Comment by Gustry** [comment]
This would be a nice feature, to make some batch transformations of many MD files.
