### ISSUE TITLE
can't live preview 

### ISSUE THREAD

**Issue by BATTZION** [jamiemcg/Remarkable#17]
hello, my system is ubuntu 15.10, my Remarkable editor can't live Preview, the live Preview option is selected.
![image](https://cloud.githubusercontent.com/assets/7559361/16617011/afe5a9aa-43b3-11e6-9eae-7296902b17ba.png)
Thanks

**Comment by jamiemcg** [comment]
Is it still not working?

**Comment by BATTZION** [comment]
now, it works, but sometimes it doesn't work. thank you.

2016-08-07 4:52 GMT+08:00 Jamie McGowan <notifications@github.com>:

**Comment by jamiemcg** [comment]
I suspect that this is caused by a network error (slow network). On launch, Remarkable downloads some resources from the Internet (MathJax, Highlight.js, CSS, Fonts, etc.). These vary depending on which style is applied. If there is no connection at all Remarkable will work without these, when there is a slow connection there may be problems (live preview won't render).

In the future these will all be stored locally.

**Comment by BATTZION** [comment]
That's it, last month my network is unstable. I thought Remarkable did't
need a network. Thank for your help.

2016-08-22 5:32 GMT+08:00 Jamie McGowan <notifications@github.com>:

**Comment by scauzhh** [comment]
Hello，My system is Ubuntu 15.04,I encounter the same problem when the network is poor.So would you like to tell me where are the resources(MathJax, Highlight.js, CSS, Fonts, etc.)  stored in my system?Then I can backup them,Thank you.

**Comment by garywill** [comment]
So "Live Preview " is an online function. I didn't know that till today I work offline.
I think remarkable should have those resources as a part of it (save on local), or I'll have to find another markdown editor.

**Comment by Uetty** [comment]
Hello, My system is Ubuntu 18.04, i encounter the same problem because my company's network is slow to connect some websites.  But it work well while i make my computer offline or use a faster network.

**Comment by anadi** [comment]
I am running 1.87 on Ubuntu 18.04. Live preview still doesnt show anything. I have very good network.

![image](https://user-images.githubusercontent.com/639546/59380019-c5290280-8d75-11e9-85f3-09a0c551fb35.png)

**Comment by frankblank** [comment]
> I am running 1.87 on Ubuntu 18.04. Live preview still doesnt show anything. I have very good network.
> 
> ![image](https://user-images.githubusercontent.com/639546/59380019-c5290280-8d75-11e9-85f3-09a0c551fb35.png)

Same here running Ubuntu 20.04 with Remarkable 1.87
it was working, but since some days no preview

**Comment by raju-bitter** [comment]
I can see the same behavior as @frankblank. I'm on Ubuntu 20.04 LTS, GNome version 3.36.2. Network connection is working, but when I launch Remarkable from command line, there are networking errors reported.
```
raju@svalbard:~/dev/emacs-setup-kinesis-keyboard$ remarkable README.md 
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Warning: Remarkable could not connect to the internet to check for updates
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
```

**Comment by bruno-cmd** [comment]
Hello
I experienced the same problem as raju-bitter and frankblank. i'm on Ubuntu 18.04LTS with release 1.87 of Remarkable.
Exactly the same error message as raju-bitter reported ...

**Comment by ericoporto** [comment]
![Screenshot from 2020-07-03 09-37-30](https://user-images.githubusercontent.com/2244442/86469965-d5a97380-bd10-11ea-97bc-3cc386c01b19.png)

I have the same problem in Ubuntu 20.04.

**Comment by egoipse** [comment]
![image](https://user-images.githubusercontent.com/2198733/93285604-a51f9480-f7ab-11ea-973a-a0c1cbb50062.png)

Same here... Ubuntu 20.04 and Remarkable 1.87

**Comment by removogel** [comment]
![image](https://user-images.githubusercontent.com/8896037/93910047-d7c41280-fd00-11ea-8286-8b7ec7aa8ba0.png)
Same issue, Ubuntu 20.04, fast Internet, Snap-Version 0+git.6f21d49

**Comment by samuelwestlake** [comment]
I have had the same issue as described. I'm using Ubuntu 20.04, I installed Remarkable using snap, and I have a good network connection, but the live preview isn't working. 

As an alternative, I downloaded the .deb from here, http://remarkableapp.github.io/linux/download.html - and installed with dpkg. However, this throes a few 'unmet decency errors' which included:
  - wkhtmltox
  - gir1.2-webkit-3.0
  - xfonts-75dpi
  - libwebkitgtk-3.0-0
I was able to install all but one of these dependencies, libwebkitgtk-3.0-0, at which point, I decided to call it a day. 
I've never had problems with remarkable when using older linux distros, so perhaps the problem stems from the fact that installing libwebkitgtk-3.0-0 on Ubuntu 20.04 is not trivial. 

I really hope a solution is found soon, I'd rather not move away from Remarkable - thanks jamiemcg for this great tool!

**Comment by michaelbukachi** [comment]
@samuelwestlake Just faced the same issue. It's definitely a webkit issue. I'm quite curious as to why snap didn't raise an error while installing :thinking:

**Comment by max11gen** [comment]
I got the same issue on Ubuntu 20.04 and remarkable 1.87. Are there any news to it?

**Comment by bruno-cmd** [comment]
Hello,
I don't know but I've been using ReText since this problem occured...

**Comment by thelxz** [comment]
same issue on Ubuntu 18.04.5 LTS and remarkable 1.87, any news?

**Comment by shufps** [comment]
is this a joke? 

4 years the same problem and no solution - thank you, I use another tool.

Btw kubuntu 20.04.

**Comment by thelxz** [comment]
Maybe the preview function is based on Okular?   After I installed Okular, everything is ok.

**Comment by Cybernetic1** [comment]
The version installed with `snap` cannot preview.  But when I installed via the `.deb` file as provided by the comment above it works.  Here's the link:
[http://remarkableapp.github.io/linux/download.html](http://remarkableapp.github.io/linux/download.html)
I am using Ubuntu 18.04.

**Comment by p-cote** [comment]
The devs been sleepy for 4 years 😂 Maybe they'll wake up one day

Anyway, Haroopad (Beta) is free and does the job very well on Ubuntu : http://pad.haroopress.com/
