### ISSUE TITLE
"Live Preview" Mode Executes JavaScript 

### ISSUE THREAD

**Issue by JohnTroony** [jamiemcg/Remarkable#175]
Remarkable "Live Preview" executes any JavaScript code embedded in the markdown file being edited. For security reasons, can this be optional ? Allowing the use to disable or enable JavaScript. 

If a user is editing a Markdown file from untrusted source, using Remarkable (Markdown Editor), he/she can be vulnerable to different  Web Attacks (using JavaScript for payload delivery).

![1](https://user-images.githubusercontent.com/4489002/27835361-70f4ca5c-60e3-11e7-8620-32210b56013f.png)
![xss](https://user-images.githubusercontent.com/4489002/27835362-70f8e95c-60e3-11e7-9f0e-4f643b712735.png)
![xx](https://user-images.githubusercontent.com/4489002/27835360-70f47200-60e3-11e7-8220-c38ba65ed766.png)

**Comment by sergiodlc** [comment]
@JohnTroony, interesting. However, I fail to see how can this be a security issue. After all, Remarkable is a desktop app that runs under user privileges. Can't a user do the same by using his web browser?

**Comment by timeraider4u** [comment]
Well, I would agree with John that the JavaScript execution should be optional.

Some guys (including myself) are using browser plug-ins to block JavaScript and other stuff from untrusted sources (e.g., NoScript, uBlock, etc.). If you download/git clone a repository and open the README file with Remarkable as your default text editor for mark-up files these browser plug-ins will not help you and you have no option to control that JavaScript actions happen automatically.

**Comment by JohnTroony** [comment]
Hey @sergiodlc , I think @timeraider4u has echoed the security concerns of having an auto-javascript loader/parser. It's a nice feature but I think it should be optional. Just loading a markdown document with Javascript on Remarkable (when Live Preview on) will execute!

By the way, I have higher expectation of Javascript executing on my browser, than a text editor :)
