### ISSUE TITLE
[Feature Request] - AppImage

### ISSUE THREAD

**Issue by CHBMB** [jamiemcg/Remarkable#178]
I love remarkable, but just installed Antergos on a new laptop and it's taking forever to compile webkitgtk to install Remarkable from the AUR.

I think it would be wonderful to have an AppImage.

**Comment by timeraider4u** [comment]
Yeah, would be quite nice to have an AppImage available, just in case...

According to https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages you can re-use Travis-CI builds for creating an AppImage:
e.g., https://github.com/mypaint/mypaint/blob/master/.travis.yml
is executing https://github.com/mypaint/mypaint/blob/master/appimage/appimage.sh

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by CHBMB** [comment]
To be honest, I'm not using Remarkable from the AUR now as they time to compile webkitgtk was so long, I really think this would be a boon for remarkable as I've not found another md editor as good.

**Comment by timeraider4u** [comment]
By the way, I think that this issue is a duplicate of #60

**Comment by CHBMB** [comment]
I'm going to close this.  It's a duplicate as pointed out by @timeraider4u and it doesn't look like Remarkable is still being developed unfortunately.
