### ISSUE TITLE
Latex equation don't appear in line

### ISSUE THREAD

**Issue by ram1123** [jamiemcg/Remarkable#180]
Dear Experts,

I am trying to write a latex equation inline but it is breaking the line and equation comes in new line. Also, If I define a equation in bullet is automatically goes in the center of line not left align.

For example:

> If there is no interference between electroweak and QCD then it should follow: $$|EWK+QCD|^2 = |EWK|^2 + |QCD|^2$$. This is main equation.

Then it breaks line for equation and equation goes to new line.

> 2. W-jets
	*  $$p_{T} (W) = 200 GeV$$
	* $$50 GeV < mW < 110 GeV$$

Also, here I want my equation to be left align instead to place it in center of line. 

Please let me know, how I can do this?

Thanks in advance for your support.

with regards,
Ram

**Comment by zoof** [comment]
Inline math is delimited by a single $ not $$.  But inline math seems to be broken for me (#202).

**Comment by ram1123** [comment]
ok... Thanks..
