### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by ronbackman** [jamiemcg/Remarkable#182]
I can't get Remarkable to install on CentOS 7.3
Python3..4 is install and pip3 is installed if needed.  I downloaded the zip package from github and unzipped it OK.  When I cd down to the bin directory and run ./remarkable, I get an error as follows.  But I checked and I do have "gtk3 " installed (via yum)

BTW, "gi" doesn't install either

I'm off to a bad start.  Any hints how to resolve these install  issues and get Remarkable up and running.  A Install Guide would be helpful

Thanks

 ./remarkable  
Traceback (most recent call last):
  File "./remarkable", line 65, in <module>
    import remarkable
  File "/home/backman/Downloads/Remarkable-master/remarkable/__init__.py", line 26, in <module>
    import gi
ImportError: No module named 'gi'
gi.require_version('Gtk', '3.0')

**Comment by jamiemcg** [comment]
Downloading and installing the RPM package from the [homepage](http://remarkableapp.github.io/linux.html) should work.

Link to download page: [http://remarkableapp.github.io/linux/download.html](http://remarkableapp.github.io/linux/download.html)
