### ISSUE TITLE
Port to webkit2gtk

### ISSUE THREAD

**Issue by dbermond** [jamiemcg/Remarkable#184]
webkitgtk is deprecated and was replaced by webkit2gtk. It was removed from Arch Linux official repositories and now is only on the AUR.

https://lists.archlinux.org/pipermail/arch-dev-public/2017-June/028900.html

It seems that Remarkable does not work with webkit2gtk. Can you please port it to use webkit2gtk?

**Comment by timeraider4u** [comment]
I would also like to see remarkable being ported to a newer webkit-gtk version. Gentoo/Linux has already marked older versions of webkit-gtk as insecure (and they might remove it from the repository soon): https://security.gentoo.org/glsa/201706-15

Any idea how big the impact of this change might be (amount of files affected)?

**Comment by timeraider4u** [comment]
Fun fact: Upstream at https://webkitgtk.org/ the new API is just called WebKit2 while the older one is called Webkit1

**Comment by timeraider4u** [comment]
Using the following bash command I get:
```bash
grep -rHil WebKit .
./pdfkit/__init__.py
./aur/remarkable/PKGBUILD
./debian/control
./remarkable/styles.py
./remarkable/RemarkableWindow.py
```
from which only `./remarkable/RemarkableWindow.py` seems to be relevant at the moment, a file with 1466 lines

**Comment by timeraider4u** [comment]
Doing some more research, I see that only 2 objects are using the namespace Webkit: [self.live_preview at line 117](https://github.com/jamiemcg/Remarkable/blob/master/remarkable/RemarkableWindow.py#L117) and [feedback_browser at line 1350](https://github.com/jamiemcg/Remarkable/blob/master/remarkable/RemarkableWindow.py#L1350). The second one is almost negligible. And searching for `self.live_preview` results in 13 matches.

**Comment by Deadolus** [comment]
Webkit2 version in https://github.com/jamiemcg/Remarkable/pull/314
