### ISSUE TITLE
There is no search (ctrl+f) ?

### ISSUE THREAD

**Issue by ProkopHapala** [jamiemcg/Remarkable#187]
Maybe I miss something but in Edit menu there is nothing like search/find/replace. Ctrl+F also does nothing. This is a basic functionality common in any text editor. Its lack hinders usability considerably.

**Comment by byohay** [comment]
Hi @ProkopHapala, I added a Find & Replace bar to Remarkable, you can find it in my [fork](https://github.com/byohay/Remarkable) :)

**Comment by breml** [comment]
@byohay did you submit this change as PR?

**Comment by byohay** [comment]
@breml I didn't, since I wanted to submit all the changes I've made one after another. Currently there are two of my PRs waiting. I could submit a PR with the find & replace, but i don't know if it will be merged as well. Moreover, I might have to deal with rebase conflicts if I tried to rebase only these changes above `master`.

**Comment by byohay** [comment]
@jamiemcg should I submit a PR? Do you still maintain this project?

**Comment by breml** [comment]
@byohay Thanks for your reply. Too bad, that your PRs are not merged. The find & replace feature would really help me a lot.

**Comment by jamiemcg** [comment]
@byohay Yes planning on inspecting existing PRs and starting to merge them

**Comment by jamiemcg** [comment]
#21

**Comment by IEC-lucy** [comment]
So,When can this function be used?

**Comment by thomas-mc-work** [comment]
@jamiemcg Maybe your project has grown to a point where it makes sense to grow the core developer group. At the moment everything depends only on one person which leads to heavy bottlenecks in the development (at the time of writing there are 98 open issues and 17 open pull requests, the oldest one from Sep 12, 2016). As I'm a developer myself I can imagine that waiting for a PR to be accepted for so long can be quite frustrating and demotivating. My proposal is to define or elect some qualified developers from the community (for example @byohay) to help you to advance this fantastic project!

**Comment by saddy001** [comment]
Is there any update on this? Remarkable seems a good editor, but no search feature really stops the show.

**Comment by LC43** [comment]
Sorry to insist, but this was marked as done, but in the latest version ( 1.87 ) i still can't find this. I saw some commits after this release, is it a matter of making a new release?

**Comment by daviddamaschk** [comment]
I had exactly the same problem with the official download.
However, this function is available in the git version. Therefore I recommend to download this version and start it with run.sh.
