### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [jamiemcg/Remarkable#191]
Could you release tarballs here on GitHub? Many thanks.

**Comment by noahrinehart** [comment]
@jamiemcg if you [tag](https://stackoverflow.com/a/18223354) the repo, it will automatically create a zip/tarball relase.

**Comment by baimafeima** [comment]
Could you also make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.
