### ISSUE TITLE
add support for .txt syntax highlighting

### ISSUE THREAD

**Issue by nchlis** [jamiemcg/Remarkable#196]
Hi and first of all thanks for the great editor.

writing something like
```
this is plain text and some more text
```
ends up automatically formatting words like 'this' and 'and'.

The problem still occurs when it should be explicitly highlighted as .txt, that is:
```text
this is plain text and some more text
```
One current "hack" is to format as another language that does not contain any of the keywords in the text, e.g. html.
![screenshot from 2017-09-17 14-37-17](https://user-images.githubusercontent.com/20245872/30520852-f1b23cc6-9bb5-11e7-92df-e3b534d381af.png)

**Comment by thomas-mc-work** [comment]
Why do you actually mark the passage as a code block then? Maybe quoting it might fit your needs to emphasize a paragraph better. 

Like this:

> this is plain text and some more text
