### ISSUE TITLE
Single newline character shoudl not break line in Markdown

### ISSUE THREAD

**Issue by michalkoza** [jamiemcg/Remarkable#207]
Using Remarkable 1.87 on ubuntu.
![selection_001](https://user-images.githubusercontent.com/2995498/31666525-d7f021dc-b34c-11e7-9ee5-e972b6b78a94.png)

**Comment by mhosken** [comment]
I agree. This is a bug. Currently one has to write paragraph length lines instead of something that is readable as plain text, which is the primary aim of Markdown.

**Comment by burtonator** [comment]
yeah.. this is really silly.  This is not supposed to happen. This is really REALLY a hard anti-feature for me.

**Comment by 0xpr03** [comment]
+1 this is a bug even more as there is a "github" Style, but github does correct linebreaks -> the preview is misleading

Github:  
![github](https://user-images.githubusercontent.com/1280209/40369189-b5824d6e-5ddd-11e8-8fcb-346a723f04c9.png)

Remarkable:
![remarkable preview](https://user-images.githubusercontent.com/1280209/40369277-dfa92004-5ddd-11e8-84dc-0bbc23fde851.png)

**Comment by egmontkob** [comment]
Came here to report the same.

I'm looking for a user-friendly Markdown viewer/editor, and can't express how disappointed I am to see that one that claims to be "The best markdown editor" doesn't get the very basics right.

Even Markdown's original [homepage](https://daringfireball.net/projects/markdown/), [source](https://daringfireball.net/projects/markdown/index.text) heavily relies on wrapping text in the source, to keep a margin at 80-ish columns.

This is a deal breaker for me, I'm moving on to other projects.

Sorry that my comment added noise only, no useful new information.

**Comment by christoferjennings** [comment]
There's a lot of great work in Remarkable. Please fix this issue.
Also, a `\` should cause a newline the same as a double-space.

**Comment by joram-berger** [comment]
Yes, that's a bug. [daringfireball.net](https://daringfireball.net/projects/markdown/syntax#block) is pretty clear on that.
In the meantime, there is a simple workaround (if you don't rely on line breaks indicated by spaces at the end of the line): The user can add a custom css snippet which renders `<br>` elements ineffective:
```css
br {
    display: none;
}
```

**Comment by mhosken** [comment]
What is the basis for closing this issue?

**Comment by jamiemcg** [comment]
1eb3c6361c55b5b5c84599d6ed1732ccbe5a95b6

**Comment by mhosken** [comment]
Great. Thanks
