### ISSUE TITLE
Can't export styled pdf

### ISSUE THREAD

**Issue by PinoTsao** [jamiemcg/Remarkable#208]
Hi, when I export styled pdf, it just failed without any helpful error info.
while plain pdf is ok.

**Comment by shoosy12** [comment]
that happens with mine as well..did you find a solution yet?

**Comment by kapad** [comment]
With me too. Though, the styled pdf gets created in the directory. The styled pdf is also correctly styled and opens fine. 

Maybe some issue with closing the file stream or something? Don't know but happy to debug if more information is needed. 

Is there an app log somewhere which I can upload to help with debugging?

**Comment by 4rshdeep** [comment]
Same happened with me too :/ . did anyone find any solution?

**Comment by shoosy12** [comment]
I contacted them and they said there will be a software update released soon as it is a known issue

M

**Comment by Cybernetic1** [comment]
I looked into the code and found that you can fix it by installing [this](https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf).  It can be as simple as:   `sudo apt install wkhtmltopdf`.  Love this software.
