### ISSUE TITLE
Ability to use external editor

### ISSUE THREAD

**Issue by TotalKrill** [jamiemcg/Remarkable#210]
I really like this viewer! 

However when I try to use an external editor, the live-view doesn't work. Also, hiding the editor by dragging the separator doesn't feel very right somehow.

I am using Linux and editing from vim.

**Comment by korken89** [comment]
I'd like to chime in and agree with @TotalKrill here.
I'm also a Vim user, and I love this viewer - just this small thing missing to make the experience seamless.
