### ISSUE TITLE
Which webkit packages does remarkable need?

### ISSUE THREAD

**Issue by PinoTsao** [jamiemcg/Remarkable#219]
I installed remarkable under Fedora workstation 27, when I start it via cli, it shows:

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

So, anyone know what should be installed?
BTW, why didn't it report the dependency issue during rpm installation?

**Comment by mbloms** [comment]
Please look at other Issues before posting new. See if any of these are related to your problem:
#193 #183 #39 
If you want to use webkit2gtk then you might want to check out #185

**Comment by mbloms** [comment]
Duplicate of #39

**Comment by jochenw** [comment]
I don't think, that this is a duplicate of #39, because I understand the  of #39 to install webkitgtk3. However, as of Fedora 27, no such RPM is available. There is only webkitgtk4. And installing that doesn't help.

**Comment by mbloms** [comment]
@jochenw maybe I was wrong about 39 then. Anyway, the real issue is that webkitgtk is old and everyone should move to webkit2gtk. Fedora dropped support for webkitgtk in 27 (from what I've read) due to the security issues. The issue I linked to has a PR, that gets Remarkable working with webkit2gtk on Fedora 27.

**Comment by jochenw** [comment]
My main issue is this: Now, that the current issue is on the table, we don't have a reproducable way to install Remarkable on Fedora 27. However, that might possibly adressed, by migrating to webkit2gtk, too.

**Comment by neteler** [comment]
Same problem on Fedora 28...

**Comment by jclaveau** [comment]
This bug may be fixed by this merge https://github.com/jamiemcg/Remarkable/pull/314#event-2789621217
