### ISSUE TITLE
Close program to write accents

### ISSUE THREAD

**Issue by davidlghellin** [jamiemcg/Remarkable#223]
When I use accents (example **á**) the program closed, this is the code in terminal to write:
```
$ remarkable 
Violación de segmento (`core' generado)
```

Archlinux 
```
$ remarkable --version
remarkable 1.87
```

**Comment by ljoli** [comment]
Hello,

I use the version 1.87 and I have the same problem.
When I try to add an accent in french language.
For example : Synthèse 
```
▶ remarkable
[1]    27960 segmentation fault (core dumped)  remarkable
```

**Comment by mbloms** [comment]
I use the same package, (I'm the maintainer of the AUR package). Wasn't able to reproduce the error. Tried Swedish and French layout. Running Manjaro, KDE Plasma.

**Comment by ljoli** [comment]
Humm **French layout** ? what it is ?

> Is this a new problem, or was it always like this?

I don't know because it's the first time I use Remarkable  😄

**Comment by misaelnieto** [comment]
Looks like this is the same bug of #222
