### ISSUE TITLE
Segmentation fault when entering non-english characters such as æ,ø,å,ñ

### ISSUE THREAD

**Issue by Northo** [jamiemcg/Remarkable#238]
Remarkable consistently crash when entering space or newline when there is a non-english character ( tested: æ,ø,å,ñ). Error:
`[1]    5253 segmentation fault (core dumped)  remarkable`
Running in gnome on 4.14.13-1-ARCH.

**Comment by mbloms** [comment]
Do you still have this issue? If yes, what's the output when you run this?
```bash
pacman -Qi python-gtkspellcheck python-pyenchant enchant
```

**Comment by Northo** [comment]
Issue solved.
