### ISSUE TITLE
Any chance of adding a 'find' function ? (plus other imporvement suggestions)

### ISSUE THREAD

**Issue by morgancoxuk** [jamiemcg/Remarkable#242]
Hi.

Really liking Remarkable as a markdown editor, on Linux at least it seems to be only using around 60MB which is great (seeing as I also have spell checking enabled)

However there is on main thing missing at present, the lack of a find option (i.e find in page...) 

Also I have these 2 other suggestions for usability improvements.

1. The preview window should scroll independently from the code window...  I have noticed that when you are editing code the preview window often scrolls to the top of the page, this is annoying when you want to check what the code changes have done to formatting, etc

2. Auto save function - I lost a few hrs work yesterday (as I am a moron that thought I had pressed the save button...) and chance of having an auto save function?

Anyway thanks for all the hard work!

**Comment by leonbr0wn** [comment]
These issues already exist:
find: https://github.com/jamiemcg/Remarkable/issues/21
scrolling: https://github.com/jamiemcg/Remarkable/issues/25
auto-save: https://github.com/jamiemcg/Remarkable/issues/155

Does no one monitor this repo or something?
