### ISSUE TITLE
Change license to GPLv2

### ISSUE THREAD

**Issue by mbloms** [jamiemcg/Remarkable#246]
If I'm not completely mistaken, since 85dd2b8 in #111 introduces code under GPLv2, the whole project must now comply with GPLv2. Either this was a mistake, and all code under GPL should be removed from the project, or the project as a whole must be licenced under GPL. Parts of the project could be licensed under MIT too, but everything must be under GPL.

As it now stands this project is in violation of GPL.

Links confirming this:
https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l
https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

**Comment by mbloms** [comment]
Looking more closely I now realise that these files are also under LGPL:
data/ui/AboutRemarkableDialog.ui
remarkable/undobuffer.py

**Comment by mbloms** [comment]
@Statici I don't understand what you're saying. Your Remarkable? What ssh password?

**Comment by Statici** [comment]
Nevermind, I'm just a dumbass that scrolled past things and posted in the wrong thread lol.

**Comment by sten0** [comment]
> my reMarkable, which I got today

@Statici @jamiemcg, given the special upper case "M" I think he's talking about one of these tablets/e-readers https://remarkable.com/ and that this issue can be closed.
