### ISSUE TITLE
Saved file is empty (0B)

### ISSUE THREAD

**Issue by Mati20187** [jamiemcg/Remarkable#248]
After saving file Remarkable crashes and saved file is empty. 
Antergos Linux, KDE Plasma

**Comment by mbloms** [comment]
Could you post the output from `pacman -Qi remarkable`?
Also, is this your first time using remarkable or did this issue come after
upgrading?
tors 8 mars 2018 kl. 20:38 skrev Mati20187 <notifications@github.com>:

**Comment by Mati20187** [comment]
It's my first time using Remarkable. 
pacman Qi output:
Name            : remarkable
Version         : 1.87-2
Description     : A free fully featured markdown editor for Linux.
Architecture    : any
URL             : http://remarkableapp.github.io
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  python-cairo  python-gobject  python-markdown  python-beautifulsoup4  python-gtkspellcheck  python-lxml
                  webkit2gtk  wkhtmltopdf  gtksourceview3
Optional Deps   : python-lxml: export to HTML format support [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : remarkable-webkit2gtk
Installed Size  : 368.00 KiB
Packager        : Unknown Packager
Build Date      : Thu Mar 8 20:46:08 2018
Install Date    : Thu Mar 8 20:46:10 2018
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

**Comment by mbloms** [comment]
I can not reproduce this on my computer.

Could you try to clone this repo and see if it works to install that instead?
https://aur.archlinux.org/remarkable-webkit2gtk.git

**Comment by Mati20187** [comment]
I can't install this package. During the install it shows me that it needs "remarkable" package. 

looking for conflicting packages...
:: remarkable-webkit2gtk and remarkable are in conflict. Remove remarkable? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: remarkable-webkit2gtk: requires remarkable

looking for conflicting packages...
:: remarkable-webkit2gtk and remarkable are in conflict. Remove remarkable? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: remarkable-webkit2gtk and remarkable are in conflict

No matter what i do (remove remarkable or not) it doesn't want to install it because they are either in conflict or need each other

**Comment by mbloms** [comment]
Ah sorry about that. You need to check out an earlier commit. I think it should be fefb51d but you could try a later too if that doesn't work. Please let me know if you get it to work that way.

**Comment by mbloms** [comment]
Ah sorry about that. You need to check out an earlier commit. I think it should be fefb51d but you could try a later too if that doesn't work. Please let me know if you get it to work that way.

**Comment by Mati20187** [comment]
This is what I've ended up with:
mati@root ~ $ cd remarkable-webkit2gtk/
mati@root ~/remarkable-webkit2gtk $ ls
0003-fixes-184-port-to-WebKit2Gtk.patch                     Remarkable-1.87                          remarkable.patch
0004-fixes-175-Live-Preview-Mode-Executes-JavaScript.patch  notes                                    src
LICENSE                                                     remarkable-webkit2gtk-1.87-5.src.tar.gz  v1.87.tar.gz
PKGBUILD                                                    remarkable.install
mati@root ~/remarkable-webkit2gtk :( $ chmod +x remarkable.install 
mati@root ~/remarkable-webkit2gtk $ ./remarkable.install

Before that, I ran makepkg -S and untared made packages. There's no Remarkable installed after this. Probably it's just my mistake, I hardly ever install packages manually

**Comment by mbloms** [comment]
Oh. You should never untar packages manually. Always install using `pacman -U <package>.tar.xz` or use `makepkg -i` for install after build. Learning how to do this manually is recommended if you're going to use the AUR.

This is what I wanted you to try:
```
> git clone https://aur.archlinux.org/remarkable-webkit2gtk.git
> git checkout fefb51d
> makepkg -si
```
If you unpacked a package manually before, you might have to remove some files if pacman complains about them, or just use `pacman -U --force` to overwrite them.

Do you think you could try to see if that works? If it doesn't, could you run start remarkable through the terminal and then post the output after it crashes?

**Comment by Mati20187** [comment]
Installation is successful but the same problem occurs as with standard remarkable. Pacman -Qi output:
Name            : remarkable-webkit2gtk
Version         : 1.87-1
Description     : A free fully featured markdown editor for Linux. - Ported to webkit2gtk
Architecture    : x86_64
URL             : http://remarkableapp.github.io
Licenses        : MIT
Groups          : None
Provides        : remarkable
Depends On      : python  python-cairo  python-gobject  python-markdown  python-beautifulsoup4  python-gtkspellcheck
                  python-lxml  webkit2gtk  wkhtmltopdf  gtksourceview3
Optional Deps   : python-lxml: export to HTML format support [installed]
Required By     : None
Optional For    : None
Conflicts With  : remarkable
Replaces        : None
Installed Size  : 427.00 KiB
Packager        : Unknown Packager
Build Date      : Sun Mar 18 18:42:44 2018
Install Date    : Sun Mar 18 18:48:49 2018
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

**Comment by mbloms** [comment]
Ok. This means there's at least nothing wrong with the new packaging. (You could switch back to regular `remarkable` in AUR.) What happens if you start remarkable in the terminal by just typing `remarkable`? This is what looks like for me when I open remarkable and save a file:
```
micke@Humlan ~> remarkable

(remarkable:25184): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(remarkable:25184): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(remarkable:25184): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
Is there any error messages before crashing?

**Comment by Mati20187** [comment]
This is what it shows after trying to save file and crashing:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/remarkable/RemarkableWindow.py", line 444, in on_menuitem_save_as_activate
    self.save_as(self)
  File "/usr/lib/python3.6/site-packages/remarkable/RemarkableWindow.py", line 458, in save_as
    file.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0105' in position 64: ordinal not in range(128)

**Comment by mbloms** [comment]
There has been some problems with people using non-english letters. It seems related to spellchecking.
Your problem also seems similar to #241.

I've moved spellcheck from "required" to "optional". Can you install the latest `remarkable` from AUR and make sure to remove `python-gtkspellcheck` with `pacman -Rs python-gtkspellcheck`?

**Comment by Mati20187** [comment]
I've removed python-gtkspellcheck but the same problem occurs. I haven't changed spellcheck to "optional", because I couldn't find this option in Remarkable

**Comment by mbloms** [comment]
@Mati20187 you misunderstood me. I meant I updated the package in AUR so that `python-gtkspellcheck` is no longer a dependency for `remarkable`.

Your problem is very weird. It seems Remarkable is trying to save your file using ascii encoding. I see no reason why it would do this. 

Have you tried opening a file saved as UTF-8 and saving it again? What's the encoding specefied in your locale?

**Comment by Mati20187** [comment]
Yes, I've tried to open file encoded as utf-8. It opens normally but when I try to save it, Remarkable saves it as empty file and crashes

**Comment by msoes** [comment]
Happened to me as well. Opened remarkable, edited for a day, saved every now and then,
and finally crashed with an empty file.

Ubuntu 18.04LTS, python 3.6.5, installed the debian package.
