### ISSUE TITLE
Problems when exporting PDF

### ISSUE THREAD

**Issue by DengHaoyu** [jamiemcg/Remarkable#251]
Like this, there is something extra at the bottom of the document when I export as PDF. Sometimes disappears, sometimes it doesn't.

Like this: Loading[MathJax]/jax/output/HTML-CSS/jax.js

[![](http://ouseof74c.bkt.clouddn.com/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20180318110525.png)]()
Here is my markdown doc
[![](http://ouseof74c.bkt.clouddn.com/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_remarkable_20180318110511.png)]()

**Comment by mmtung** [comment]
I have the same issue with version 1.87 under arch Linux.
