### ISSUE TITLE
preview live is not working, remarkable 1.87 mint 18.3 (ubuntu 16.04)

### ISSUE THREAD

**Issue by jontis** [jamiemcg/Remarkable#252]
As says, when writing text, it is not rendered in "live preview" that stays empty. Text is properly rendered when exported as pdf och viewed with external preview.

**Comment by jontis** [comment]
When further investigating, by changing Style, sometimes you get to see the preview text for a brief second before it disappears.

**Comment by jontis** [comment]
Changing the style with "custom css" can also make the text in live preview appear for a second before it disappears.

**Comment by TristanFaureIGN** [comment]
Same for me... :'(
