### ISSUE TITLE
Numbered list showing roman numerals instead of numbers

### ISSUE THREAD

**Issue by victory118** [jamiemcg/Remarkable#269]
The numbered list is not working as expected.

When I type:

1. Item 1
2. Item 2
3. Item 3

The output is:

i. Item 1
ii. Item 2
iii. Item 3

Why is this happening? I am using all of the default settings.

**Comment by ssi112** [comment]
This is **still** happening. Online documentation shows numbers as expected, but it still outputs roman numerals in display. Are there any plans to fix this?

**Comment by phil-h-dlt** [comment]
This is part of the style configuration. If you choose a different style (e.g. Markdown instead of Github) then the numbering changes to normal (arabic) numerals.

**Comment by ssi112** [comment]
Okay, made the style change and it works. However, GitHub doesn't display it that way so not certain why that style would have that display setting. Anyway, thanks for the reply.

**Comment by rphair** [comment]
I don't see why this was closed.  A numbered list (each item beginning with `1.`) in Remarkable, when selecting the _Github (Default)_ style from the menu, appears in the Remarkable preview with lowercase Roman numerals (exactly as described above) while with the proper numbers on Github.  So the preview is generated incorrectly with respect to Github.

Software: version `1.87` on Linux (`.deb`)

**Comment by Jaaz7** [comment]
Go to this [website](https://www.editpad.org/tool/invisible-character), copy the invisible character and paste it before writing the number, like this:
‎ 1.
‎ 2.
‎ 3.

**Comment by jk-1** [comment]
This bug is still there. Not fixed.

The numbered list is not working as expected.

When I type:

    Item 1
    Item 2
    Item 3

The output is:

i. Item 1
ii. Item 2
iii. Item 3

Why is this happening? I am using all of the default settings.

Version 1.95, OS Ubuntu 22 LTS.
