### ISSUE TITLE
AsciiMath

### ISSUE THREAD

**Issue by mlopezgva** [jamiemcg/Remarkable#271]
Hello!

I would like to ask for the implementation of the [AsciiMath](http://asciimath.org/) mathematical formulæ syntax, as it is more "markdown-like" and much, much easier to type.

Of course, LaTeX should continue to be supported, but in my opinion, as MarkDown main goal is to make easier to write documents, an easier syntax for math could be added to the "standard".

**MathJax** is good, but `asciiMath` is simple and covers many common scenarios, I would suggest to allow both in the Options.

Just to make a point, see the difference between TeX and asciiMath with these examples:
- Cauchy-Schwarz Inequality, this is terrific:
  - TeX:
    `\[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]`
  - asciiMath:
    `(sum_(k=1)^n a_kb_k)^2 <= (sum_(k=1)^n a_k^2) (sum_(k=1)^n b_k^2)`

![captura de pantalla de 2016-07-14 17 01 13](https://cloud.githubusercontent.com/assets/996070/16855241/d0114eae-49ea-11e6-8336-41c1a189cc66.png)
- Lorenz:
  - TeX:
    `\dot{x} = \sigma(y-x) \\ \dot{y} = \rho x - y - xz \\ \dot{z} = -\beta z + xy`
  - asciiMath
    `dotx = sigma(y-x)`
    `\doty = rho x-y - xz`
    `\dotz = -beta z + xy`
- Probability:
  - TeX:
    `\[P(E)   = {n \choose k} p^k (1-p)^{ n-k } \]`
  - asciiMath:
    `P(E) = ((n),(k)) p^k (1-p)^(n-k)`

![captura de pantalla de 2016-07-14 17 18 59](https://cloud.githubusercontent.com/assets/996070/16855268/fa423bb6-49ea-11e6-9642-b78d58a108bf.png)
- And, of course, the quadratic formula:
  - TeX:
    `-b \pm \sqrt{b^2 - 4ac} \over 2a`
  - asciiMath
    `x=-b+- sqrt(b^2-4ac)/2a`

![captura de pantalla de 2016-07-14 17 18 33](https://cloud.githubusercontent.com/assets/996070/16855277/02ed5e62-49eb-11e6-887b-61325ceb70b3.png)

Some more examples comparing the same formulas in Markdown Plus help:

| Núm. | LaTeX | length | ASCII Math | length |
| --: | --- | --: | --- | --: |
| 1 | `\dfrac{ \tfrac{1}{2}[1-(\tfrac{1}{2})^n] }{ 1-\tfrac{1}{2} } = s_n` | 66 | `(1/2[1-(1/2)^n])/(1-(1/2))=8_n` | **30** |
| 2 | `\oint_C x^3\, dx + 4y^2\, dy` | 28 | `oint_Cx^3 dx+4y^2 dy` | 21 |
| 3 | `2 = \left( \frac{\left(3-x\right) \times 2}{3-x} \right)` | 57 | `2=(((3-x)xx2)/(3-x))` | **20** |
| 4 | `\sum_{m=1}^\infty\sum_{n=1}^\infty\frac{m^2\,n} {3^m\left(m\,3^n+n\,3^m\right)}` | 80 | `sum_(m=1)^oosum_(n=1)^oo(m^2 n)/(3^m(m3^n+n3^m)` | **48** |

And the last one is so big (169 characters), I must put it as a code block...

```
phi_n(\kappa) =
 \frac{1}{4\pi^2\kappa^2} \int_0^\infty
 \frac{\sin(\kappa R)}{\kappa R}
 \frac{\partial}{\partial R}
 \left[R^2\frac{\partial D_n(R)}{\partial R}\right]\,dR
```

And, ASCIImath version:

```
phi_n(kappa) = 1/(4pi^2 kappa^2)
 int_0^oo (sin(kappa R))/(kappa R)
 del/(del R)
[R^2 (del D_n (R))/(del R)] del R
```

Its not so long (112 characters, including spaces, I could've put it in a oneliner:

`phi_n(kappa) = 1/(4pi^2 kappa^2)  int_0^oo (sin(kappa R))/(kappa R)  del/(del R) [R^2 (del D_n (R))/(del R)] del R`

See the difference? And there's another one: I had only peeked at the docs to see he "name" of the 'oint'. **Everything else** I was able to type without help, it's "natural" (something LaTeX is definetly not ;)).

**Comment by jfellus** [comment]
:+1:  This would be very nice !
