### ISSUE TITLE
doesn't work in f29, ValueError: Namespace WebKit not available

### ISSUE THREAD

**Issue by hhlp** [jamiemcg/Remarkable#279]
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 127, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

**Comment by jesusferm** [comment]
I have the same problem.

**Comment by ekuester** [comment]
I have the same problem.

**Comment by andypillip** [comment]
Same issue here, I don't feel comfortable just building from that source.

**Comment by ekuester** [comment]
@andypillip 
OK, you have to trust the cited source ... The installation procedure is not so difficult, surely you must have some experience with the terminal. But then remarkable is fully usable.

**Comment by andypillip** [comment]
@ekuester Hallo Erich.

I'd like to review and diff the code to the original before I build my package.
Aside from me not trusting the source the file is no longer available (404).

**Comment by ekuester** [comment]
@andypillip Hallo Andy,
please see again #282 (I added the needed files for download)
