### ISSUE TITLE
Will finally install in Fedora 29

### ISSUE THREAD

**Issue by ekuester** [jamiemcg/Remarkable#282]
Under Fedora 28 I installed remarkable from repo rpm-sphere and the programm worked flawlessly. Before upgrading to Fedora 29 I had to remove the application, otherwise upgrading failed. Now I want to install anew and get the message
`Problem: conflicting requests - nothing provides python(abi) = 3.6`
Any ideas where to get python(abi) ?

**Comment by ekuester** [comment]
OK, I disabled the rpm-sphere repo and installed with the

**Comment by kbknapp** [comment]
For some strange reason I had to manually extract the source RPM, and build. After which it worked flawlessly for me.

```
$ wget http://download.opensuse.org/repositories/home://zhonghuaren/Fedora_28/src/remarkable-1.87-6.1.src.rpm
$ rpm2cpio | cpio -idmv
$ mkdir -p ~/rpmbuild/{RPMS,SRPMS,SOURCES,SPECS,BUILD}
$ mv *.patch ~/rpmbuild/SOURCES
$ mv *.tar.gz ~/rpmbuild/SOURCES
$ mv remarkable.spec ~/rpmbuild/SPECS
$ rpmbuild -ba ~/rpmbuild/SPECS/remarkable.spec
$ sudo dnf install ~/rpmbuild/RPMS/noarch/remarkable-1.87-6.1.noarch.rpm
```
If the command looks successful, but nothing is output to `~/rpmbuild/RPMS/` check your `/tmp` sometimes it can get spit out there.

```
$ sudo find /tmp -type f -name "remarkable*.rpm"
```

**Comment by ekuester** [comment]
The above mentioned website is no more available. Enclosed you will find the needed patch files (withdraw the .txt extension). If the files have again their original names follow the procedure of kbknapp above using the Remarkable-1.87.tar.gz from Releases.
[remarkable.spec.txt](https://github.com/jamiemcg/Remarkable/files/2758959/remarkable.spec.txt)
[0003-fixes-184-port-to-WebKit2Gtk.patch.txt](https://github.com/jamiemcg/Remarkable/files/2758961/0003-fixes-184-port-to-WebKit2Gtk.patch.txt)
[0004-fixes-175-Live-Preview-Mode-Executes-JavaScript.patch.txt](https://github.com/jamiemcg/Remarkable/files/2758962/0004-fixes-175-Live-Preview-Mode-Executes-JavaScript.patch.txt)

**Comment by bluebat** [comment]
https://github.com/rpmsphere/source/raw/master/r/remarkable-1.87-6.1.src.rpm

**Comment by ekuester** [comment]
@bluebat 
A little more comment would be helpful for those who do not know the rpmsphere repo ... I saw only chinese letters in the GitHub notification and first thought then is. caution.

**Comment by tigos2** [comment]
It's worked on Fedora 30!

**Comment by PhilippeFerreiraDeSousa** [comment]
Hi, it could be helpful to just correct the RPM on the official website.

**Comment by fwelland** [comment]
Didn't work (Namespace WebKit not available) in Fedora 31.   

That said, the src.rpm procedure worked pretty well.

**Comment by ekuester** [comment]
@fwelland  Did you follow the installation procedure given by kbknapp above? And yes, you must ensure that webkitgtk4 is installed, worked here flwlessly under fedora 31 as `webkit2gtk3-2.28.1-3.fc31.x86_64` ...

**Comment by fwelland** [comment]
No the one above it, the one that just took the src.rpm, installed it and rebuilt it and then re-installed the freshly built RPM.      That said, I used the src.rpm from rpmsphere, just a few posts above; 1.87-6.1  

The original bin, (having no WebKit errors) I downloaded was 1.87-1 was from here:  https://remarkableapp.github.io/files/remarkable-1.87-1.rpm.   I just followed the download links on the various pages to get to that.

**Comment by ekuester** [comment]
For testing I remove my working remarkable installation and use the source file from rpmsphere. I unpack the file into the right directories manually and started the compilation, which worked without problems. Then I did the installation with
 `sudo dnf install ./rpmbuild/RPMS/noarch/remarkable-1.87-6.1.noarch.rpm`
and Remarkable starts without problems. I think you will have to use `dnf` for installing and maybe the lower version `webkit2gtk3-2.26.4-1.fc31` will be no problem ...

**Comment by fwelland** [comment]
The 2nd test I did on my laptop it never had Remarkable on it.    I just download the RPM (1.87-1) and tried it as an experiment as I noticed fully patched F31 did have the newer webkit on it...  That is when I got the NameSpace GtkSource issue.          

NOTE:  not really a problem, I can fix via rpmbuild process from above -- I don't really need MD editor on that rig anyway...just providing some feed back if it helps..

Oh would you look at that Fedora 32 is out ;)

**Comment by polemon** [comment]
> Oh would you look at that Fedora 32 is out ;)
Does the problem still persist on F32, or does it automagically fix itself, when I upgrade to F32?
I'm still on F31 on this machine.

**Comment by ekuester** [comment]
@polemon No problems in building and installing the RPM on F32 ... Take the sources from the rpm sphere repo, untar it (SPEC file into SPECS, the remaining files into SOURCES) and build the RPM in the above described way. On F32 python-3.8 is used and there will be installed three dependencies
```
python3-markdown
python3-pdfkit
wkhtmltopdf
```
Good luck!
