### ISSUE TITLE
Does not install on debian buster

### ISSUE THREAD

**Issue by amtriorix** [jamiemcg/Remarkable#286]
Deb package does not install on Debian Buster due to webkit version.

dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:
  Package gir1.2-gtksource-3.0 is not installed.
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.

dpkg: error processing package remarkable (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.61) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for libglib2.0-0:amd64 (2.58.1-2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

**Comment by condor-webdev** [comment]
Same problem here on Kali 4.19

**Comment by jclaveau** [comment]
Same on Ubuntu 19.04

**Comment by LuisRodrigoArce-Valdes** [comment]
Just to add that:
`sudo apt install -f`
doesn't seem to fix this issue, at least on Ubuntu 19.04

**Comment by aborrell** [comment]
Download and install this packages from Debian stretch or ubuntu 18.04:
dpkg -i libicu57_57.1-6+deb9u2_amd64.deb 
dpkg -i libwebkitgtk-3.0-0_2.4.11-3_amd64.deb
Do the same with:
gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb
gir1.2-webkit-3.0_2.4.11-3_amd64.deb
And finally:
dpkg -i remarkable_1.87_all.deb
This worked for Ubuntu Disco and Debian Sid

**Comment by szlewa** [comment]
> Deb package does not install on Debian Buster due to webkit version.

I've just migrated to Debian Buster and i'm waiting for a deb package compatible with this webkit version . It would be nice to be able to use this tool with Buster version of Debian.
Can we have an idea of how much time this could take ?
Many thanks.

**Comment by v1993** [comment]
@szlewa Last commit in this repository was more than one year ago. I guess it can be called dead :disappointed:.

**Comment by szlewa** [comment]
@v1993 thanks, i hope it's not the case, but you are right it's a bad sign for people who expect an update for Debian buster. Wondering if i will not return to stretch finally.

**Comment by jclaveau** [comment]
This issue is fixed by https://github.com/jamiemcg/Remarkable/pull/314 but which is not merged

**Comment by Deadolus** [comment]
Alternatively you might consider using the snap I created for #317:
sudo snap install remarkable

**Comment by estiveljr** [comment]
> Alternatively you might consider using the snap I created for #317:
> sudo snap install remarkable

works well in debian buster
