### ISSUE TITLE
Nightmode

### ISSUE THREAD

**Issue by liborty** [jamiemcg/Remarkable#287]
Ticking the Nightmode in Linux does nothing.
No settings in the menus.
Is there any way to change the default background colour of the editor window? 
The styles apply only to the preview.

**Comment by saeedghsh** [comment]
same for me... Ubuntu 16.04, installed from `.deb` file.

**Comment by jamiemcg** [comment]
Night mode only works when using a Gtk theme that supports a dark style (e.g. Numix themes)
