### ISSUE TITLE
zoom level not persisted

### ISSUE THREAD

**Issue by brainchild0** [jamiemcg/Remarkable#295]
# Steps to reproduce

1.  Make a copy of the application configuration file (`~/.remarkable/remarkable.settings` on Linux systems).
1.  Open the application.  Begin typing text.  Notice size of body content. 
1.  Move zoom level up several notches.  Notice new size of text.
1.  Exit application.
1.  Compare new configuration file to saved copy.

# Expected Behavior

Configuration parameters have changed.

# Actual Behavior

Configuration parameters are unchanged.

# Version  

**Version:** 1.87
**Platform:** Linux Mint 19.1

# Further Information

## Configuration File

In one test, I captured the settings while the application was closed.

~~~
~/.remarkable$ cat remarkable.settings 
{'css': '', 'font': 'Sans 12', 'line-numbers': False, 'live-preview': True, 'nightmode': False, 'statusbar': True, 'style': 'markdown', 'toolbar': False, 'vertical': False, 'word-wrap': True}
~~~

I then opened the application, and changed zoom level, enabled the toolbar, and enabled line numbers.  Notice that  two parameters changed.

~~~
~/.remarkable$ cat remarkable.settings 
{'css': '', 'font': 'Sans 12', 'line-numbers': True, 'live-preview': True, 'nightmode': False, 'statusbar': True, 'style': 'markdown', 'toolbar': True, 'vertical': False, 'word-wrap': True}
~~~

## Attempted Resolution

A resolution to  this problem has already  been attempted in  #117, however, no changes apparently were merged upstream.

## Other issues

Per #294, more comprehensive support for zoom level should be considered.  Each time I open any  window in this application, I must show the toolbar, adjust the zoom level such that the text is large enough to see, then hide the toolbar.  Related features, such as inheriting the zoom level from the parent window, might be considered.

**Comment by snowman** [comment]
In 2020, this feature has not implemented yet :(
