### ISSUE TITLE
Projects | MultiTab

### ISSUE THREAD

**Issue by StoffelCPR** [jamiemcg/Remarkable#298]
I've been using remarkable for a few projects and like the feel of it.

What I'm missing is, is that I sometimes want to open a project folder with multiple markdown files to work on(e.g. git Wikis) therefore it would be nice, if remarkable supports either project folders or something like a Multi Tab window, or both.

**Comment by daesu** [comment]
Would like to see this too. +1

**Comment by b-m-f** [comment]
+1

**Comment by violetu** [comment]
+1

**Comment by AStepaniuk** [comment]
Partially related to #24
