### ISSUE TITLE
code tag inside HTML tag

### ISSUE THREAD

**Issue by drmad** [jamiemcg/Remarkable#30]
Hello,

Thanks for make this nice piece of software, it's really cool :-) I found this issue: When you write this:

```
<div>
'''
hello there
'''
</div>
```

(I've replace the backticks for apostrophes here), the Preview pane shows this:

```
wzxhzdk:0
```

no matter what content I put inside the triple backticks, it always shows that `wzxhzdk:0` code.  I'm using 1.75 version installed from .deb.

¡Saludos desde Perú!

**Comment by jamiemcg** [comment]
Seems to be related to [this](https://github.com/waylan/Python-Markdown/issues/222). Will look into it.
