### ISSUE TITLE
Application is not installed

### ISSUE THREAD

**Issue by Mracobes9** [jamiemcg/Remarkable#303]
Hi. When i try to install application, i got error: "unsatisfied dependencies: gir1.2-webkit-3.0". My system is kubuntu 19.04

**Comment by pipatth** [comment]
Got the same error. Seems like 19.04 doesn't have gir1.2-webkit-3.0 on the repo. Try this: https://www.reddit.com/r/Ubuntu/comments/bfx93y/1904_and_webkit30/

**Comment by luksfarris** [comment]
Thanks @pipatth your explanation works for me in Ubuntu 19. Seems like Disco only has support for gi 2.0 webkit 4.0

Adding `deb http://us.archive.ubuntu.com/ubuntu/ cosmic universe` to `/etc/apt/sources.list` is enough to allow you to install Remarkable. Just don't forget to revert your changes to the sources list file. Might make sense for this project to migrate to the new version of webkit in the future, but that's not for the scope of this issue.

**Comment by jclaveau** [comment]
Dup of https://github.com/jamiemcg/Remarkable/issues/286
