### ISSUE TITLE
Why is the preview pane always blank?

### ISSUE THREAD

**Issue by KimbingNg** [jamiemcg/Remarkable#308]
Yesterday when I was using remarkable, I found that the code suddenly did not have automatic highlighting. I didn't care at the time. When I used it the next day, I found that no matter what I wrote, there was no change in preview, and preview was always blank.

I tried reinstalling, but it didn't work, and preview was always blank.

**Comment by zocker-160** [comment]
have you tried reloading the preview page?

rightclick > reload

sometimes it's blank for me and when I start typing it suddenly pops up

**Comment by zhihaocheng** [comment]
the same problem. And when it is blank, the reload button becomes gray.
