### ISSUE TITLE
Unable to use 'remarkable'

### ISSUE THREAD

**Issue by alex4200** [jamiemcg/Remarkable#312]
I just installed `remarkable` via

    sudo dpkg -i remarkable_1.87_all.deb

in a Ubuntu machine (16.04.6), but when I try to use it on a .rst file I get an error
```

Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 26, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

How can I fix this problem?

**Comment by JamiesonWarner** [comment]
I encountered this also, Alex. There is a problem with the `gi` package in Python 3.6. I did the following workaround:

1. `vim /usr/bin/remarkable`
2. Change the first line to `#! /usr/bin/python3.5`

**Comment by Deadolus** [comment]
@alex4200 Make sure you have python3-gi installed
