### ISSUE TITLE
code preview has light background when using Solarized Dark

### ISSUE THREAD

**Issue by skewty** [jamiemcg/Remarkable#32]
I'm running v1.75 and when I select Solarized Dark as theme the code in preview pane has a light background.  When I went copied the CSS for Solarized Dark from `remarkable/styles.py` and pasted it into my Custom CSS and applied it, the code had a dark background.

**Comment by jamiemcg** [comment]
Improved in version 1.87

[Remarkable homepage](http://remarkableapp.github.io/linux.html)

Will completely redo all styles in near future
