### ISSUE TITLE
Cannot install .deb on Ubuntu 19.10

### ISSUE THREAD

**Issue by upondeep** [jamiemcg/Remarkable#323]
![image](https://user-images.githubusercontent.com/15573251/70759859-caabd900-1d15-11ea-9ade-f6fcdb6e5eb0.png)

**Comment by stewbond** [comment]
Noticed the same thing in debian 10 (buster).  A little investigation shows the *.deb package has a dependency on `gir1.2-webkit-3.0`.

Debian dropped support for gir1.2-webkit-3.0 in buster (debian 10)
Ubuntu dropped support for gir1.2-webkit-3.0 in bionic (ubuntu 18.04)

The replacement is `gir1.2-webkit2-4.0`.  I haven't tried running `remarkable` with `gir1.2-webkit2-4.0` yet.

**Comment by yerbestpal** [comment]
`gir1.2-webkit2-4.0` is already installed in Ubuntu 19.10 but the package insists on `gir1.2-webkit-3.0`.

**Comment by aminelch** [comment]
same problem here. 😞
I have been trying to install these missing packages manually, but I have got an **unmet dependency error**

```
 sudo apt install  gir1.2-gtksource-3.0 python3-markdown gir1.2-webkit2-4.0 python3-bs4 wkhtmltopdf 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-webkit2-4.0 is already the newest version (2.26.2-0ubuntu0.19.10.1).
gir1.2-webkit2-4.0 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 python3-bs4 : Depends: python3-soupsieve but it is not going to be installed
               Recommends: python3-lxml but it is not going to be installed
 python3-markdown : Depends: python3-packaging but it is not going to be installed
                    Recommends: python3-pygments but it is not going to be installed
 remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by sevku** [comment]
> Not a solution, but the snap works perfectly.

unfortunately not for me

**Comment by aminelch** [comment]
Honestly, I stop using this tool 😭😭
by doing a simple search I have discovered a cool markdown editor called **stackedit.io**

**Comment by chrestomanci** [comment]
> Honestly, I stop using this tool sobsob
> by doing a simple search I have discovered a cool markdown editor called **stackedit.io**

slackedit is non free, It is only free as in beer while in beta, after which it will be paid, except there is no proposed pricing published anywhere.

I would consider investing the time to learn slackedit if the cost will be reasonable, but not if the author will be asking $100 once it is out of beta, and right now there is no information.

Also, the bug tracker for slackedit has over 500 open issues, so if you are looking for a bug free product, then you won't get one any time soon!

**Comment by pcfirebeats** [comment]
Same thing happens here, fails to install the deb on Pop_OS 19.10

"The following packages have unmet dependencies:
  remarkable: Depende: gir1.2-webkit-3.0 but it is not installable"

**Comment by nigiord** [comment]
Any workaround?

**Comment by pcfirebeats** [comment]
> Any workaround?

You can use the snap.

**Comment by phgachoud** [comment]
> > Any workaround?
> 
> You can use the snap.

could you point out a link and more about what you mean about "snap"?

**Comment by pcfirebeats** [comment]
> > > Any workaround?
> > 
> > 
> > You can use the snap.
> 
> could you point out a link and more about what you mean about "snap"?

https://snapcraft.io/remarkable

**Comment by pragomer** [comment]
Same here. Deb file does not install on Ubuntu 20.04 or Debian 10.
Problem with the snap package: it install fine, but pdf export and html export always fail. :-(
