### ISSUE TITLE
Issue: Imags not shown when exporting to PDF (Ubuntu 18.10)

### ISSUE THREAD

**Issue by niccoloraspa** [jamiemcg/Remarkable#326]
Hello,
I have an issue when exporting my markdown notes to pdf.
The images are not shown in the pdf and I get the missing file icon.

The images are saved locally in the `img/` folder.

**Comment by nikever** [comment]
I've found this: https://github.com/jamiemcg/Remarkable/issues/236
And i think it's because I'm using relative paths. 
It would be great if I didn't have to change paths.

Thanks!

**Comment by matjazvencelj** [comment]
I'm not sure where on the line between feature request and a bug we are... but... this is really important!, I think.
