### ISSUE TITLE
missing dependencies when trying to install

### ISSUE THREAD

**Issue by sevku** [jamiemcg/Remarkable#333]
Trying to install Remarkable using the .deb package on a Ubuntu 18.04 system, the following output is generated:

```
$ sudo dpkg -i remarkable_1.87_all.deb 
(Lese Datenbank ... 438889 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von remarkable_1.87_all.deb ...
Entpacken von remarkable (1.87) über (1.87) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von remarkable:
 remarkable hängt ab von python3-markdown; aber:
  Paket python3-markdown ist nicht installiert.
 remarkable hängt ab von python3-bs4; aber:
  Paket python3-bs4 ist nicht installiert.
 remarkable hängt ab von gir1.2-webkit-3.0; aber:
  Paket gir1.2-webkit-3.0 ist nicht installiert.
 remarkable hängt ab von wkhtmltopdf; aber:
  Paket wkhtmltopdf ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes remarkable (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für mime-support (3.60ubuntu1) werden verarbeitet ...
Trigger für desktop-file-utils (0.23-4ubuntu1) werden verarbeitet ...
Trigger für libglib2.0-0:amd64 (2.60.4-0ubuntu0.19.04.1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 remarkable
```

**Comment by rthickling** [comment]
Hi, I've just installed it on a (derivative of) Ubuntu 19.10.
The sequence of required packages is:
- libjavascriptcoregtk-3.0-0_2.4.11-3ubuntu3_amd64.deb
- libicu60_60.2-3ubuntu3_amd64.deb
- libwebkitgtk-3.0-0_2.4.11-3ubuntu3_amd64.deb
- gir1.2-javascriptcoregtk-3.0_2.4.11-3ubuntu3_amd64.deb
- gir1.2-webkit-3.0_2.4.11-3ubuntu3_amd64.deb

They can all be found from https://packages.ubuntu.com/.

**Comment by MichaelTiernan** [comment]
I will add a datapoint here. I downloaded the deb file from the webpage and tried to install and it complained that:

```
remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
```

So I installed a newer version of the dependency but `remarkable` still complains looking for a lower version:

```
Note, selecting 'gir1.2-webkit2-4.0' for regex 'gir1.2-webkit'
The following additional packages will be installed:
  gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4
The following NEW packages will be installed:
  gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0
. . .
```

```
sudo apt install ./remarkable_1.87_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'remarkable' instead of './remarkable_1.87_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by MichaelTiernan** [comment]
I missed that this is the same as #323

**Comment by sevku** [comment]
@MichaelTiernan 323 or 332?

**Comment by MichaelTiernan** [comment]
I'd have to reinvestigate but my initial scan of the reports I saw implied a common thread.

While not authoritative I thought it was wise to raise a flag on my own but report that showed a possible commonality.

I'll try to review it more carefully later and see what I can provide for evidence.

**Comment by sigg3** [comment]
Get the same on Pop_OS 20.04 LTS:

```
 dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
```

and `sudo apt-get install gir1.2` shows that (newer version) is installed:
```
gir1.2-webkit2-4.0 is already the newest version (2.28.2-0ubuntu0.20.04.1).
gir1.2-webkit2-4.0 set to manually installed.
```

**Comment by thebigG** [comment]
>  dpkg: dependency problems prevent configuration of remarkable:
>  remarkable depends on gir1.2-webkit-3.0; however:
>   Package gir1.2-webkit-3.0 is not installed.

Have the same exact issue. Running POP OS with Ubuntu 20.04 as well.

**Comment by ssi112** [comment]
Upgraded to Pop 20.04 and now cannot install Remarkable. Same issue as stated above:
**Not installed: unmet dependencies gir1.2-webkit-3.0**

Tried:
$ sudo apt-get install -f gir1.2-webkit-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gir1.2-webkit-3.0
E: Couldn't find any package by glob 'gir1.2-webkit-3.0'
E: Couldn't find any package by regex 'gir1.2-webkit-3.0'

Is there a solution / workaround?
Thanks

**Comment by sevku** [comment]
@ssi112, try installing it with snap, it works for me.
