### ISSUE TITLE
inline math equation by using single '$' is not working

### ISSUE THREAD

**Issue by quzim** [jamiemcg/Remarkable#341]
I installed Remarkable 1.8.7 on Debian8 , I'm trying to insert inline math equation by using single dollar signs on both side of the equation,But it's not works.
In the help file --markdown tutorial, it still shows wrong.

**Comment by impopular-guy** [comment]
Hello @quzim 
This issue has been solved [here](https://github.com/jamiemcg/Remarkable/issues/160#issuecomment-378986185)

**Comment by ben2talk** [comment]
I don't think this is fixed.
Of great interest to me is the ability to easily write maths equations.
$x^3$ for example WORKS in VSCode, and Typora.
I noticed this whilst following a tutorial... it didn't render.

**Comment by Steven-nagisa-Y** [comment]
I have installed Remarkable 1.87 on my RPi, and I can't type inline math expressions with $ either.

like $x^2 + y^2 = z$
