### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by robguinness** [jamiemcg/Remarkable#348]
Hi,

Just discovered this project. It looks really great, and seems to fill a much needed gap in good markdown editors with export capability to HTML/PDF. But is the project still active? There seems to be no new release in three years. Are you looking for a new maintainer?

**Comment by pragomer** [comment]
Very good question. Got the same view: Fills greatly a gap in good markdown editors...
If development would be not active anymore, this would be a pitty. I found no editor thats such good.
Unfortunately since Ubuntu 20.04 and Debian 10 the deb-package and snap-package both dont work at all (the snap at exporting....).
I hope dev will go on.

**Comment by robguinness** [comment]
If @jamiemcg is unable to continue development / maintenance, would he be willing to take on a new maintainer?

**Comment by rmackinnon** [comment]
Can second @robguinness and @pragomer feels on this.  This app fills an incredible gap. As a Gentoo/Sabayon user, I ended up just cloning and setting it up by hand. While I'm a python coder, my skills are all backend, but would still be willing to help test and bug bash.

**Comment by robguinness** [comment]
Maybe the best thing to do is just fork it. I have managed to get things working on Xubuntu 20.04. I could make a fork and share what I did, if that helps someone.

**Comment by pragomer** [comment]
Hi robguinness,

yes it would help me a lot if you could offer a working version / fork for (X)ubuntu 20.04. Would be great. It would help me a lot.
Thank you so much.

**Comment by thomas-mc-work** [comment]
Yes, please @robguinness, go ahead and fork it! Many users are waiting for someone to take over. See also the discussion: https://github.com/jamiemcg/Remarkable/issues/187#issuecomment-336867844

I guess there are some people who would like to join or support you, once you've started.

**Comment by matt-hu** [comment]
I have a fork [here](https://github.com/matt-hu/Remarkable) which I'm willing to accept PRs on...
