### ISSUE TITLE
Source release?

### ISSUE THREAD

**Issue by Luke-Nukem** [jamiemcg/Remarkable#35]
For the sake of easy packaging for inclusion in distros (and building on openbuild), can you please do source package release on github?

**Comment by ghisvail** [comment]
I second this. Please consider tagging commits corresponding to stable releases at least.

**Comment by maffblaster** [comment]
I am third to support this. We (distribution package maintainers) need clear versions to be able to support. Being a Python project, this fits the Python ethos.
