### ISSUE TITLE
Cannot install on Kubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [jamiemcg/Remarkable#351]
sudo dpkg -i remarkable_1.87_all.deb 
    (Reading database ... 318255 files and directories currently installed.)
    Preparing to unpack remarkable_1.87_all.deb ... 
    Unpacking remarkable (1.87) over (1.87) ... 
    dpkg: dependency problems prevent configuration of remarkable:
     remarkable depends on gir1.2-webkit-3.0; however:
      Package gir1.2-webkit-3.0 is not installed.
    
    dpkg: error processing package remarkable (--install):
     dependency problems - leaving unconfigured
    Processing triggers for mime-support (3.64ubuntu1) ... 
    Processing triggers for desktop-file-utils (0.24-1ubuntu2) ... 
    Processing triggers for libglib2.0-0:amd64 (2.64.2-1~fakesync1) ... 
    Processing triggers for hicolor-icon-theme (0.17-2) ... 
    Errors were encountered while processing:
     remarkable

**Comment by appleyuchi** [comment]
https://blog.csdn.net/appleyuchi/article/details/107022438
here's the tutorial to install on xubuntu 20.04
