### ISSUE TITLE
No live preview Ubuntu 20.04

### ISSUE THREAD

**Issue by dfrancocci** [jamiemcg/Remarkable#357]
Hi - I've just installed Remarkable on Ubuntu 20.04, and there is no live preview. 

![Screenshot from 2020-07-12 23-12-27](https://user-images.githubusercontent.com/29356405/87257762-9e1b9380-c495-11ea-82e4-f24bc81a6c9e.png)

Seems there are a lot of comments saying the same in the reviews on Ubuntu Software.

**Comment by biojames** [comment]
I can confirm this, installation on Ubuntu 20.04 through the snap gives the view reported by @dfrancocci.
Attempt to install through the .deb file gives dependencies that cannot be satisfied (gir1.2-webkit-3.0 is "not installable" on 20.04, only gir1.2-webkit2-4.0).

**Comment by ak2766** [comment]
Eleven days later ( from first report by @dfrancocci ) - any update on this one?

I'd really prefer not to have to go the route that @biojames ( thanks for the workaround ) has taken but will be forced to if there's no response here within the week - yes, I'm patient.

**Comment by ak2766** [comment]
Another workaround by @frankblank [here](https://github.com/jamiemcg/Remarkable/issues/17#issuecomment-641791356) is to use [typora.io](https://typora.io) until this issue with Remarkable is sorted.

**Comment by jonnius** [comment]
Installed as a snap, I see the same issue and the following message in terminal:
```
Warning: Remarkable could not connect to the internet to check for updates
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
```

**Comment by tannuchoudhary** [comment]
Facing the same problem, there is no live preview in my ubuntu 18.04

**Comment by rogelioprieto** [comment]
I have the same problem, I can't get live preview. I'm using Ubuntu 20.04

**Comment by yingjiewei** [comment]
the same problem in centos 7.9

**Comment by mikeperalta1** [comment]
+1 Ubuntu 20.10

**Comment by romintomasetti** [comment]
> +1 Ubuntu 20.10 via snap
> 
> But simply cloning the repo instead and executing run.sh works for me.

This solution worked for me as well !

**Comment by ox-rjaumain** [comment]
+1 Ubuntu 20.10 via snap

**Comment by brioja** [comment]
Still exists with ubuntu 20.10 via snap.

**Comment by Victinyx** [comment]
Still exists on Ubuntu 20.04 via snap

**Comment by ch-n** [comment]
Ubuntu 20.4
+1 no live preview with installation via snap
+1 error with dependencies that cannot be satisfied when installing from .deb

Simply cloning the git repo should not  be considered the solution...

**Comment by ebrahimkarimi** [comment]
same issue here

its an awesome idea to use Markdown for notes but why did you stop supporting on it 🥺

**Comment by massimilianodesimone** [comment]
Live Preview is not working on Ubuntu 20.04.3 LTS

**Comment by eldarj** [comment]
Preview not working on Ubuntu 21.10 either

**Comment by botscripter** [comment]
Preview does not work as well on Fedora Linux 35 installed over snap.

**Comment by mdg1019** [comment]
I don't understand why this was closed when it's still an issue. :(

**Comment by npbcts** [comment]
Ubuntu 22.04
+1 no live preview with installation via snap

**Comment by LiberaLongo** [comment]
same in Ubuntu 22.04.1 snap,

i also tryed to clone and run run.sh but that is given:
./run.sh
Traceback (most recent call last):
  File "/home/libera/Scaricati/PROGRAMS/Remarkable/bin/remarkable", line 65, in <module>
    import remarkable
  File "/home/libera/Scaricati/PROGRAMS/Remarkable/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/home/libera/Scaricati/PROGRAMS/Remarkable/remarkable/RemarkableWindow.py", line 29, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by seanvaleo** [comment]
Still an issue

**Comment by ak2766** [comment]
Looks like the OP closed this and any more noise in here might not be picked up by the software author.  I just happened to revisit this after many moons and I see it's still an issue - :(.

I'll go the route of the others here and use either `typora` or `clone and execute run.sh`.

**Comment by david-zamora-minderest** [comment]
Still an issue in ubuntu 22.04.
