### ISSUE TITLE
The deb package cannot be installed under current Ubuntu 20.04

### ISSUE THREAD

**Issue by johann-petrak** [jamiemcg/Remarkable#361]
```
reparing to unpack remarkable_1.87_all.deb ...
Unpacking remarkable (1.87) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
```
BUT:
```
$ sudo apt install gir1.2-webkit-3.0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gir1.2-webkit-3.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gir1.2-webkit-3.0' has no installation candidate
```

It seems in 20.04 only gir1.2-webkit2-4.0 is available, see https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=gir1.2-webkit&searchon=names

Just cloning the GitHub repo and running from there works fine though!

**Comment by nevarsin** [comment]
Tested and verified on Linux Mint 20 too.

**Comment by weiss-d** [comment]
Same on Pop!_OS 20.04

**Comment by ChiliPaneer** [comment]
Yeah it's not working on Ubuntu 20.04 for me aswell.

If you just want to get it working you can also use:
`snap install remarkable` 
which is an unofficial upload from [here](https://snapcraft.io/remarkable).

**Comment by weiss-d** [comment]
@ChiliPaneer, thanks! I installed it this way (also tried --beta flag) but the preview half of the window doesn't show up. `External preview` option doesn't work either.
![image](https://user-images.githubusercontent.com/62437174/92887120-ea933900-f41c-11ea-833d-2834b1a0e8b0.png)
Console log shows error:
`Gtk-Message: 10:51:41.603: Failed to load module "appmenu-gtk-module"`
Looks like the problem is similar to this:
https://askubuntu.com/questions/1268368/snap-store-giving-error-failed-to-load-module-appmenu-gtk-module

**Comment by lwbaqueros** [comment]
I have the same problem in Ubuntu 20.04. The .deb package is not able to install Remarkable. I installed it from `snap` but having the same problem with the preview in blank and the warning `Failed to load module "appmenu-gtk-module"`. I installed both packages `appmenu-gtk3-module` and  `appmenu-gtk3-module` but it does not get rid of the warning.

**Comment by dBenedek** [comment]
The same problem here on Ubuntu 20.04 LTS. 
Still, the best solution is cloning the repo and using that way.

**Comment by CaptainPackers** [comment]
> The same problem here on Ubuntu 20.04 LTS.
> Still, the best solution is cloning the repo and using that way.

What does that mean eaxactly? How do you clone a repo and use it that way? I'd like to use remarkable, but Kubuntu 20.04 is my daily driver, and I'm having the same issues as everyone above is reporting, the deb package won't install, and the snap package has a disabled preview pane.

**Comment by dBenedek** [comment]
> > The same problem here on Ubuntu 20.04 LTS.
> > Still, the best solution is cloning the repo and using that way.
> 
> What does that mean eaxactly? How do you clone a repo and use it that way? I'd like to use remarkable, but Kubuntu 20.04 is my daily driver, and I'm having the same issues as everyone above is reporting, the deb package won't install, and the snap package has a disabled preview pane.

```bash
git clone 'https://github.com/jamiemcg/Remarkable.git' && cd Remarkable
./run.sh
```

You can also create a `.desktop` file probably in your `~/.local/share/applications` directory for the bash file, if you want to have an icon of Remarkable on your desktop.

**Comment by CaptainPackers** [comment]
Here's what I get when I run ./run.sh from Remarkable. I've replaced my user name with "Me" below. What do I need to do to resolve this? Thanks.

myHost:~/Remarkable$ ./run.sh
Traceback (most recent call last):
  File "/home/Me/Remarkable/bin/remarkable", line 65, in <module>
    import remarkable
  File "/home/Me/Remarkable/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/home/Me/Remarkable/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0

**Comment by lauguillier** [comment]
It's a missing dependency ... try `sudo apt install gir1.2-gtksource-3.0`

**Comment by lauguillier** [comment]
> Here's what I get when I run ./run.sh from Remarkable. I've replaced my user name with "Me" below. What do I need to do to resolve this? Thanks.
> 
> myHost:~/Remarkable$ ./run.sh
> Traceback (most recent call last):
> File "/home/Me/Remarkable/bin/remarkable", line 65, in
> import remarkable
> File "/home/Me/Remarkable/remarkable/**init**.py", line 30, in
> from remarkable import RemarkableWindow
> File "/home/Me/Remarkable/remarkable/RemarkableWindow.py", line 26, in
> gi.require_version('GtkSource', '3.0')
> File "/usr/lib/python3/dist-packages/gi/**init**.py", line 132, in require_version
> raise ValueError('Namespace %s not available for version %s' %
> ValueError: Namespace GtkSource not available for version 3.0

It's a missing dependency ... try `sudo apt install gir1.2-gtksource-3.0`

**Comment by raffraffraff** [comment]
I'm posting [this workaround](https://github.com/raffraffraff/docker-remarkable) in any of the issues related to installing Remarkable:

**Comment by moof-moof** [comment]
Thank you! It seems to work alright in Ubuntu 20.04 now (at last).

I closed the parallel issue  #371: **Remarkable .deb package won't install on Ubuntu 20.04**

**Comment by mrmikee** [comment]
> Thank you! It seems to work alright in Ubuntu 20.04 now (at last).
> 

Still not working for Pop_OS 20.04 and the "official deb" file.

**Comment by kkyucon** [comment]
> Also I repackages the deb for Ubuntu 20.04, you can find it here: https://github.com/seiferteric/remarkable_debfix

Works with 20.04

**Comment by bmullan** [comment]
The debfix works with Ubuntu 22.04 also

**Comment by JontomXire** [comment]
A 4 year old issue, fairly fundamental, and still not fixed.

Looking around on the internet, Remarkable gets the best reviews, but I am not sure I want to invest time in software that is no longer properly supported.
