### ISSUE TITLE
Manjaro : only unknown character

### ISSUE THREAD

**Issue by sducouedic** [jamiemcg/Remarkable#363]
Hello, 

I installed yesterday Remarkable via snap on manjaro. The application replaces every symbols by the unknown character: 
![Screenshot_20201007_162630](https://user-images.githubusercontent.com/10992808/95344429-ef32fc00-08b9-11eb-9826-1339fa86b3d3.png)

**Comment by bfomascitti** [comment]
Hello, did you resolve it? I have same issue here.
Tks

**Comment by so7fie** [comment]
Nope, still an open question

**Comment by Moilleadoir** [comment]
Disappointing since the AUR package doesn’t run at all.

I think this is [a known problem](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/103) with some snap apps — some problem with fontconfig that can be fixed by updating the base files.
