### ISSUE TITLE
Can't put fenced code block inside list

### ISSUE THREAD

**Issue by fahadh4ilyas** [jamiemcg/Remarkable#365]
what I want to do is this

1. first list
    ```python
    import pandas as pd
    ```
2. second list
    1. sub list
        ```python
        print('example')
        ````
3. third list

But, I can't do it using remarkable. This is what I do to produce the example:
```
1. first list
    ```python
    import pandas as pd
    ```
2. second list
    1. sub list
        ```python
        print('example')
        ````
3. third list
```

**Comment by kkyucon** [comment]
Same problem here.

Found a workaround but can't use syntax highlighting.

Here's how I got fenced code blocks indented:
```sh
* Indented code block

        # apt update
```

One line break and two `Tab`s
