### ISSUE TITLE
ValueError: Namespace GtkSource not available for version 3.0

### ISSUE THREAD

**Issue by phanos-engineer** [jamiemcg/Remarkable#368]
Unable to run application missing python package. I don't know what package is missing from python.
```
$ remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0
```

**Comment by 1994sugar** [comment]
> Unable to run application missing python package. I don't know what package is missing from python.
> 
> ```
> $ remarkable 
> Traceback (most recent call last):
>   File "/usr/bin/remarkable", line 65, in <module>
>     import remarkable
>   File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
>     from remarkable import RemarkableWindow
>   File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
>     gi.require_version('GtkSource', '3.0')
>   File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 129, in require_version
>     raise ValueError('Namespace %s not available for version %s' %
> ValueError: Namespace GtkSource not available for version 3.0
> ```

I have the same problem

**Comment by fontz** [comment]
From the error traceback to line 26 of `RemarkableWindow.py`, it is looking for `GtkSource 3.0` which isn't installed. 

- Check your installed GtkSource verison. For Ubuntu/Debian based systems: `dpkg -l | grep 'gtksource'` (It's 4 for Ubuntu 20.04).
- Change to the installed version in `gi.require_version('GtkSource', '3.0')` in `remarkable/RemarkableWindow.py`.

**Comment by 1994sugar** [comment]
Thans a lot, I will try it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fontz"<notifications@github.com&gt;; 
发送时间: 2020年12月4日(星期五) 下午3:34
收件人: "jamiemcg/Remarkable"<Remarkable@noreply.github.com&gt;; 
抄送: "296055705"<296055705@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jamiemcg/Remarkable] ValueError: Namespace GtkSource not available for version 3.0 (#368)





 
From the error traceback to line 26 of RemarkableWindow.py, it is looking for GtkSource 3.0 which isn't installed.
  
Check your installed GtkSource verison. For Ubuntu/Debian based systems: dpkg -l | grep 'gtksource' (It's 4 for Ubuntu 20.04).
 
Change to the installed version in gi.require_version('GtkSource', '3.0') in remarkable/RemarkableWindow.py.

**Comment by amoskong** [comment]
I also touched this problem on Fedora 33, gtksourceview4-4.8.0-1.fc33.x86_64 had been installed in the past.

I tried to install gtksourceview3-3.24.11-4.fc33.x86_64  by `sudo dnf install gtksourceview3`, the problem was solved :-)

**Comment by zhetaoj** [comment]
> From the error traceback to line 26 of `RemarkableWindow.py`, it is looking for `GtkSource 3.0` which isn't installed.
> 
>     * Check your installed GtkSource verison. For Ubuntu/Debian based systems: `dpkg -l | grep 'gtksource'` (It's 4 for Ubuntu 20.04).
> 
>     * Change to the installed version in `gi.require_version('GtkSource', '3.0')` in `remarkable/RemarkableWindow.py`.

Followed this post and resolved the issue by changing 'gi.require_version('GtkSource', '3.0')' to 'gi.require_version('GtkSource', '4')' in 'remarkable/RemarkableWindow.py'. 
Also did the following: 
sudo apt-get install -y libwebkit2gtk-4.0-dev
pip3 install BeautifulSoup4
pip3 install markdown

system: Pop OS 20.04

**Comment by GameO7er** [comment]
I had this problem and after checking the log, I figured out it's because of `.deb` dependencies. 

```
gameover@home:~$ sudo dpkg -i remarkable_1.18_.deb 
Selecting previously unselected package remarkable.
(Reading database ... 289262 files and directories currently installed.)
Preparing to unpack remarkable_1.18_.deb ...
Unpacking remarkable (1.87) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:
  Package gir1.2-gtksource-3.0 is not installed.
 remarkable depends on gir1.2-webkit2-4.0; however:
  Package gir1.2-webkit2-4.0 is not installed.
 remarkable depends on yelp; however:
  Package yelp is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.

dpkg: error processing package remarkable (--install):
 dependency problems - leaving unconfigured
Processing triggers for libglib2.0-0:amd64 (2.66.8-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 remarkable
```



so I wrote this answer [here](https://askubuntu.com/a/1414290/1174362) from this issue #371 

Hope this helps

**Comment by GameO7er** [comment]
I had this problem and after checking the log, I figured out it's because of `.deb` dependencies. 

```
gameover@home:~$ sudo dpkg -i remarkable_1.18_.deb 
Selecting previously unselected package remarkable.
(Reading database ... 289262 files and directories currently installed.)
Preparing to unpack remarkable_1.18_.deb ...
Unpacking remarkable (1.87) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:
  Package gir1.2-gtksource-3.0 is not installed.
 remarkable depends on gir1.2-webkit2-4.0; however:
  Package gir1.2-webkit2-4.0 is not installed.
 remarkable depends on yelp; however:
  Package yelp is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.

dpkg: error processing package remarkable (--install):
 dependency problems - leaving unconfigured
Processing triggers for libglib2.0-0:amd64 (2.66.8-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 remarkable
```



so I wrote this answer [here](https://askubuntu.com/a/1414290/1174362) from this issue #371 

Hope this helps

**Comment by uniuuu** [comment]
> I also touched this problem on Fedora 33, gtksourceview4-4.8.0-1.fc33.x86_64 had been installed in the past.
> 
> I tried to install gtksourceview3-3.24.11-4.fc33.x86_64 by `sudo dnf install gtksourceview3`, the problem was solved :-)

In Fedora 38 `dnf install gtksourceview3` solved the issue.

**Comment by uniuuu** [comment]
> I also touched this problem on Fedora 33, gtksourceview4-4.8.0-1.fc33.x86_64 had been installed in the past.
> 
> I tried to install gtksourceview3-3.24.11-4.fc33.x86_64 by `sudo dnf install gtksourceview3`, the problem was solved :-)

In Fedora 38 `dnf install gtksourceview3` hasn't solved the issue.

**Comment by Sergo3682** [comment]
#### My OS is OpenSUSE 15.5 

What worked for me was downloading the following packages:
```
typelib-1_0-GtkSource-4;
typelib-1_0-WebKit2-4_1;
python3-beautifulsoup4;
```

and changing lines 26 and 27 in``` Remarkable/remarkable/RemarkableWindow.py``` to the following:
```
gi.require_version('GtkSource', '4')
gi.require_version('WebKit2', '4.1')
```

The point is that there should be ```*.typelib``` files in your system at the path ```/usr/lib64/girepository-1.0/```. Their names should coincide with the names specified in the errors.
You can check the version of such files via
```
import gi
from gi.repository import GtkSource
```
Here the script will warn you that the ```gi.require_version('GtkSource', '<version>')``` command must be used first and will indicate what version of the files you have.
