### ISSUE TITLE
Export pdf (styled) problem. Ubuntu 20.04

### ISSUE THREAD

**Issue by cafernandezlo** [jamiemcg/Remarkable#370]
preview is ok but exporting a PDF (styled) is not working properly, seems like some of the chucks (baash) are badly formed. I tried cloning the repo, with snap but the same problem arise and also have problems to install the deb package as mentioned in previous issues.

**Comment by mikeperalta1** [comment]
+1

Tried to run in debug mode but didn't see any useful information. I'm on Ubuntu 20.10 using a repo clone (commit 1ed83780fa011badca3c22f28e34475eb0d36564).

Console only outputs the following:

```
mike@bedroom:~/Documents$ remarkable --verbose
DEBUG:remarkable: set_up_logging() 'logging enabled'
--verbose does not exist, creating it
```

**Comment by mikeperalta1** [comment]
As a temporary workaround, you can export to HTML, then use the ```wkhtmltopdf``` tool to convert to PDF:

```bash
$ wkhtmltopdf --enable-local-file-access my-document.html my-document.pdf
```

As you can see in the image below, it's not perfect. But at least it's something:

![image](https://user-images.githubusercontent.com/26490778/109098571-769cd280-76d6-11eb-96df-da828de50824.png)

**Comment by mikeperalta1** [comment]
Poking around, I've just noticed Remarkable is using pdfkit version 0.4.1, while the latest is 0.6.1

Just a thought.
