### ISSUE TITLE
Remarkable .deb package won't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by moof-moof** [jamiemcg/Remarkable#371]
The install depends on gir1.2-webkit-3.0, which is not an available package for Ubuntu 20.04 "Focal Fossa".

**Comment by Stormur** [comment]
I can confirm. At the same time, `gir1.2-webkit-4.0` is installed.

**Comment by andreas83** [comment]
see also #361

**Comment by jringoot** [comment]
I confirm, same issue for Debian 10: gir1.2-webkit-4.0 is installed, gir1.2-webkit-3.0, which is not an available package for Debian 10.
But Release 1.9, as downloaded from GIT and run from ./run.sh appears to work flawlessly

**Comment by CaptainPackers** [comment]
How do you get Release 1.9?

**Comment by raffraffraff** [comment]
I'm posting [this workaround](https://github.com/raffraffraff/docker-remarkable) in any of the issues related to installing Remarkable:
However, since [this issue](https://github.com/jamiemcg/Remarkable/issues/378) was is 5 months old and never got an answer, it might be time to find another editor

**Comment by glennb-mitre** [comment]
[Here](https://github.com/seiferteric/remarkable_debfix) is a fix from Eric Seifert that fixes the dependency problem and repackages remarkable in a new .deb.

**Comment by moof-moof** [comment]
> [Here](https://github.com/seiferteric/remarkable_debfix) is a fix from Eric Seifert that fixes the dependency problem and repackages remarkable in a new .deb.

Thank you! It seems to work alright in Ubuntu 20.04 now (at last).

**Comment by Stormur** [comment]
> [Here](https://github.com/seiferteric/remarkable_debfix) is a fix from Eric Seifert that fixes the dependency problem and repackages remarkable in a new .deb.

Thanks! It works fine! even if by now I had elected another program to handle markdown :grimacing:
