### ISSUE TITLE
No "Find" functionality?

### ISSUE THREAD

**Issue by noam1023** [jamiemcg/Remarkable#373]
I am running v 1.87 running on ubuntu 20.04. Package was installed using apt.

I can't see where the find/replace menu item (or keyboard shortcut) is.
Pressing CTRL F does nothing. (no matter if I am at the left or right pane).
CTRL S works fine. so keyboard shortcut is working in general.

**Comment by evanmarzahn** [comment]
I came to make the same complaint but on 1.87 installed on Arch via the AUR.
