### ISSUE TITLE
DEB instillation fails on Ubuntu due to missing dependencies 

### ISSUE THREAD

**Issue by tawfiek** [jamiemcg/Remarkable#379]
I tried to install Remarkable using DEB file provided into the Download page  [here](https://remarkableapp.github.io/linux/download.html)

however it fails due to missing dependencies.
``` 
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:
  Package gir1.2-gtksource-3.0 is not installed.
 remarkable depends on python3-markdown; however:
  Package python3-markdown is not installed.
 remarkable depends on python3-bs4; however:
  Package python3-bs4 is not installed.
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.
```  
I think it's a good idea to add some instruction to install the app into Linux systems with dependency because it fails completely silently if the file opened  via GUI.

**Comment by raffaem** [comment]
Same here. I am on Ubuntu 20.10.

There is a `gir1.2-webkit2-4.0` in the repositories. But not `gir1.2-webkit2-3.0`.

**Comment by raffaem** [comment]
This package is only [available for xenial (16.04)](https://packages.ubuntu.com/search?keywords=gir1.2-webkit2-3.0&searchon=names&suite=all&section=all). From bionic (18.04) and up [there is only](https://packages.ubuntu.com/search?keywords=gir1.2-webkit2-4.0&searchon=names&suite=all&section=all) the `4.0` version.

**Comment by Drugwash2** [comment]
There is a gir1.2-webkit-3.0 package for Ubuntu 18.04 (Linux Mint 19.x) **[here](https://pkgs.org/download/gir1.2-webkit-3.0)**.
I already had it installed from some previous package, all this missed was **wkhtmltopdf** which **GDebi** picked up and installed automatically.
Remarkable then installed fine on my Linux Mint 19.2 and is nothing short of... uhm... remarkable. Now...

Just fired up a virtual Mint 20.1 and tested. Installed through GDebi **in order**:
- [gir1.2-javascriptcoregtk-3.0_2.4.11-3ubuntu3_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/universe/w/webkitgtk/gir1.2-javascriptcoregtk-3.0_2.4.11-3ubuntu3_amd64.deb)
- [libicu60_60.2-3ubuntu3.1_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3.1_amd64.deb)
- [libjavascriptcoregtk-3.0-0_2.4.11-3ubuntu3_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/universe/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.11-3ubuntu3_amd64.deb)
- [libwebkitgtk-3.0-0_2.4.11-3ubuntu3_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/universe/w/webkitgtk/libwebkitgtk-3.0-0_2.4.11-3ubuntu3_amd64.deb)
    which at install time required other 3 dependencies (automatically picked by GDebi from official repository):
        - enchant 1.6.0-11.3build1
        - libegl1-mesa 20.2.6-0ubuntu0.20.04.1
        - libenchant1c2a 1.6.0-11.3build1
- [gir1.2-webkit-3.0_2.4.11-3ubuntu3_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/universe/w/webkitgtk/gir1.2-webkit-3.0_2.4.11-3ubuntu3_amd64.deb)
- **[remarkable_1.87_all.deb](https://remarkableapp.github.io/files/remarkable_1.87_all.deb)**
    which at install time required other 10 dependencies, automatically resolved by GDebi:
        - libqt5positioning5 5.12.8+dfsg-0ubuntu1
        - libqt5printsupport5 5.12.8+dfsg-0ubuntu1
        - libqt5qml5 5.12.8-0ubuntu1
        - libqt5quick5 5.12.8-0ubuntu1
        - libqt5sensors5 5.12.8-0ubuntu1
        - libqt5webchannel5 5.12.8-0ubuntu1
        - libqt5webkit5 5.212.0~alpha4-1ubuntu2
        - python3-markdown 3.1.1-3
        - python3-pygments 2.3.1+dfsg-1ubuntu2.2
        - wkhtmltopdf 0.12.5-1build1

After all this - uncomparably easier and less frustrating than the **five hours** wasted earlier in searching one - **any** - Markdown viewer - this remarkable package once installed started up and is ready for work.

So, if you can go through all the steps above precisely in that order you should be able to install Remarkable on Ubuntu 20.x or derivatives. Good luck!

**Comment by huntergregal** [comment]
any update on making this not a PITA for ubuntu 20?

**Comment by berrak** [comment]
I tried to install 'Remarkable' on Debian Bullseye (aka Debian v11).

        # apt install ./remarkable_1.87_all.deb
        Reading package lists... Done
        Building dependency tree... Done
        Reading state information... Done
        Note, selecting 'remarkable' instead of './remarkable_1.87_all.deb'
        Some packages could not be installed. This may mean that you have
        requested an impossible situation or if you are using the unstable
        distribution that some required packages have not yet been created
        or been moved out of Incoming.
        
        The following information may help to resolve the situation:
        
        The following packages have unmet dependencies:
         remarkable : Depends: gir1.2-webkit-3.0 but it is not installable

On my Debain v11 machine Webkit2 is installed by default.

    # aptitude search gir1.2-webkit
    i A gir1.2-webkit2-4.0            - Web content engine library for GTK - GObject introspection data

From Debian package information page: https://packages.debian.org/search?keywords=gir1.2-webkit-3.0:
They are lots of missing dependencies if you dig into it, but the takeaway is that it looks like Debian maintainers will not keep this 'gir1.2-webkit-3.0' version alive from 'stretch' (aka Debian v9) -- and that version is already pretty old.

**Comment by paulocoghi** [comment]
Same here. I tried to install on Ubuntu 20.04, and got:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by raffraffraff** [comment]
_Sigh_. This is why people have started using horrible solutions like Snap, AppImage, Flatpak: properly packaging applications is hard. For now, the easiest solution for me is to build a Docker container `FROM ubuntu:bionic`, and run it with the `.Xauthority` and X11 socket mounted.

**Comment by huntergregal** [comment]
i actually went to `Typora` and love it. It actually works and installs.

**Comment by raffraffraff** [comment]
Looks like there was a minor update 5 months ago, but yeah... crickets. 

For what it's worth, I created a [project to build and run a Remarkable docker container](https://github.com/raffraffraff/docker-remarkable). It should work on any flavor of Linux.
