### ISSUE TITLE
No document in right pane...

### ISSUE THREAD

**Issue by timindaburgh** [jamiemcg/Remarkable#390]
Perhaps a newbie error (sorry for this), but I've downloaded 1.87 and ran it, but the right hand pane is empty.
http://remarkableapp.github.io/linux.html says that Live Preview will be used to generate the output. Another place said that Screen Share would be used to generate the  output. There is simply no output on my instance.

Installation on Ubuntu 20.04

![Screenshot from 2022-03-07 13-58-02](https://user-images.githubusercontent.com/9344018/157099919-15afae33-65c3-4263-ae0a-18c15f957f4e.png)

**Comment by CarlyRaeJepsenStan** [comment]
I, too, have this issue.  I really want to use this!

**Comment by timindaburgh** [comment]
Has anyone found a way for this to work in Ubuntu 20.04?

**Comment by botscripter** [comment]
Same issue here on Fedora Linux 35 installed over snap.

**Comment by FreaxMATE** [comment]
Any errors, when starting from terminal?

**Comment by CarlyRaeJepsenStan** [comment]
@FreaxMATE Yeah, see the error I linked to above #379
