### ISSUE TITLE
Inline MathJax on Linux

### ISSUE THREAD

**Issue by s-merchant** [jamiemcg/Remarkable#391]
![Screenshot from 2022-03-08 13-30-05](https://user-images.githubusercontent.com/16521595/157302499-d5a7946a-cebe-4e12-97c3-d23979716388.png)

Wasn't getting inline $'s to produce anything in my doc.  Thought I'd done something wrong, so I checked the tutorial, but it seems that the problem is there, too.  Just installed from .deb on Ubuntu.

**Comment by jaghili** [comment]
Fixed has been suggested, see #160

**Comment by vvitez** [comment]
Same issue on Arch, newest version from the AUR. Please fix this, pretty please.
