### ISSUE TITLE
No font on snap install

### ISSUE THREAD

**Issue by ramenspazz** [jamiemcg/Remarkable#394]
I just installed remarkable 0+git.6f21d49, and upon launching there is no font rendered, only blank boxes where text should be.

System information:
Fedora 36
Kernel: x86_64 Linux 5.17.5-300.fc36.x86_64
DE: GNOME 42.1
CPU: AMD Ryzen 5 4500U 
GPU: AMD RENOIR (LLVM 14.0.0, DRM 3.44, 5.17.5-300.fc36.x86_64)

Runtime output:
Cannot get default EGL display: EGL_BAD_PARAMETER
WaylandCompositor requires eglCreateImage and eglDestroyImage.
Nested Wayland compositor could not initialize EGL
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc

**Comment by nmvega** [comment]
> I just installed remarkable 0+git.6f21d49, and upon launching there is no font rendered, only blank boxes where text should be.
> 
> System information: Fedora 36 Kernel: x86_64 Linux 5.17.5-300.fc36.x86_64 DE: GNOME 42.1 CPU: AMD Ryzen 5 4500U GPU: AMD RENOIR (LLVM 14.0.0, DRM 3.44, 5.17.5-300.fc36.x86_64)
> 
> Runtime output: Cannot get default EGL display: EGL_BAD_PARAMETER WaylandCompositor requires eglCreateImage and eglDestroyImage. Nested Wayland compositor could not initialize EGL /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc

I have this issue, too (exactly as you described it). I tried **Snap** and **RPM** versions atop **Fedora O/S**, and both have the same outcome: Square boxes where information should be. Did you ever find a solution for this?

**Comment by chris5335** [comment]
I am getting the exact same behavior with the same runtime output as @ramenspazz.  I installed it via Snap on Fedora 37.

**Comment by ramenspazz** [comment]
@nmvega No solution as of yet. I have still been getting the same issue as of the 9th of December, 2022.
