### ISSUE TITLE
Cannot install .deb file on Linux Mint 21 / Ubuntu 22

### ISSUE THREAD

**Issue by prubin73** [jamiemcg/Remarkable#397]
Gdebi reports an unsatisfiable dependency: gir1.2-webkit-3.0. The Canonical repo contains gir1.2-webkit2-4.0 (installed on my system) and gir1.2-webkit2-4.1 (not installed).

**Comment by cjcdev** [comment]
Same issue

**Comment by frroossst** [comment]
Same here on linux mint 20.3

**Comment by celsomsilva** [comment]
Same issue here. Other option doesn't run: "snap install remarkable"(Ubuntu has issues with it too), but Mint prevents the 'snapd' instalation.

**Comment by hetica** [comment]
Same issue on Debian bookworm

**Comment by resotek** [comment]
I just tried the .deb file with Remarkable 1.87 on Linux Mint 21.2, and the dependency error is still there.

**Comment by Fr-Dae** [comment]
**On Lubuntu 24.04**
```properties
dae@dae-gl753vd:~/Téléchargements$ sudo dpkg -i remarkable_1.87_all.deb 
Sélection du paquet remarkable précédemment désélectionné.
(Lecture de la base de données... 301262 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de remarkable_1.87_all.deb ...
Dépaquetage de remarkable (1.87) ...
dpkg: des problèmes de dépendances empêchent la configuration de remarkable :
 remarkable dépend de python3-markdown; cependant :
  Le paquet python3-markdown n'est pas installé.
 remarkable dépend de python3-bs4; cependant :
  Le paquet python3-bs4 n'est pas installé.
 remarkable dépend de gir1.2-webkit-3.0; cependant :
  Le paquet gir1.2-webkit-3.0 n'est pas installé.
 remarkable dépend de wkhtmltopdf; cependant :
  Le paquet wkhtmltopdf n'est pas installé.

dpkg: erreur de traitement du paquet remarkable (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour gnome-menus (3.36.0-1.1ubuntu3) ...
Traitement des actions différées (« triggers ») pour bamfdaemon (0.5.6+22.04.20220217-0ubuntu5) ...
Rebuilding /usr/share/applications/bamf-2.index...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.27-2build1) ...
Traitement des actions différées (« triggers ») pour libglib2.0-0t64:amd64 (2.80.0-6ubuntu1) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
Des erreurs ont été rencontrées pendant l'exécution :
 remarkable
```
could you use `gir1.2-webkit2-4.1` ? and solve the problem 
=)

**Comment by Fr-Dae** [comment]
in addition, someone know the difference betwen `python3-markdown` and ` python3-markdown2` ?

**Comment by Fr-Dae** [comment]
- https://github.com/jamiemcg/Remarkable/issues/400
- https://github.com/jamiemcg/Remarkable/issues/403
- https://github.com/seiferteric/remarkable_debfix?tab=readme-ov-file

```python
cd ~/src
git clone https://github.com/jamiemcg/remarkable
ln -s ~/src/remarkable/run.sh ~/bin/remarkable
cd ~/my/work/directory
remarkable file.md
```

**Comment by MWP** [comment]
Two years later, this still isn't resolved? :(

**Comment by celsomsilva** [comment]
> Two years later, this still isn't resolved? :(
😲 Wow! I completely forgot about that. On the same day, I moved on to another option. Forget it, that's in the past 😂

**Comment by celsomsilva** [comment]
> Two years later, this still isn't resolved? :(

😲 Wow! I completely forgot about that. On the same day, I moved on to another option. Forget it, that's in the past 😂

**Comment by Fr-Dae** [comment]
th

**Comment by MWP** [comment]
> > Two years later, this still isn't resolved? :(
> 
> 😲 Wow! I completely forgot about that. On the same day, I moved on to another option. Forget it, that's in the past 😂

Yup, i did too.

**Comment by MWP** [comment]
Confirmed that the new build installed nicely under LinuxMint 22 / Ubuntu Noble.
Thankyou.
