### ISSUE TITLE
Remarkable's uninstallable in Ubuntu 22.04!

### ISSUE THREAD

**Issue by rjyaba** [jamiemcg/Remarkable#398]
It was uninstallable using Debian GUI installers like "GDebi Package Installer" and "Software Installer" due to this error...
Error:
      Dependency is not satisfiable:  gir1.2-webkit-3.0

**Comment by AdolphGithub** [comment]
+1

**Comment by bmullan** [comment]
I can't be sure but I think you might be able to install:

**
> sudo apt-get install gir1.2-webkit2-4.0
**

as it is **webkit 4.0** which should satisfy "_Dependency is not satisfiable: gir1.2-**webkit-3.0**_"

**Comment by martinschweingruber** [comment]
> > $ **sudo apt-get install gir1.2-webkit2-4.0**
> 
> as it is **webkit 4.0** which should satisfy "_Dependency is not satisfiable: gir1.2-**webkit-3.0**_"

still if `gir1.2-webkit2-4.0` is installed it keeps asking for `gir1.2-webkit2-3.0`

**Comment by rjyaba** [comment]
Thank you for the email.

I have installed it lately on my laptop running Ubuntu 22.04.  Got a
working (fixed) version from Github thru the link below:
https://github.com/seiferteric/remarkable_debfix
