### ISSUE TITLE
No Preview

### ISSUE THREAD

**Issue by GNUqb114514** [jamiemcg/Remarkable#399]
I cant see the Live Preview on my Remarkable.
And my terminal says many ***strange logs*** like this:
```
Cannot get default EGL display: EGL_BAD_PARAMETER
WaylandCompositor requires eglCreateImage and eglDestroyImage.
Nested Wayland compositor could not initialize EGL
Warning: Remarkable could not connect to the internet to check for updates
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
...
```
etc.

Why this? How can I end it?

**Comment by AlexOnFOSS** [comment]
Same here using Ubuntu-Studio 20.04 and the snap version of remarkable:

Warning: Remarkable could not connect to the internet to check for updates
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: : symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcesssymbol lookup error: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess
: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc

(remarkable:17309): GLib-GIO-WARNING **: 09:08:51.396: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
Traceback (most recent call last):
  File "/snap/remarkable/5/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 574, in _click_move_button
    if self._deferred_check:  self._check_deferred_range(True)
AttributeError: 'SpellChecker' object has no attribute '_deferred_check'
Traceback (most recent call last):
  File "/snap/remarkable/5/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 189, in <lambda>
    lambda entry, menu:self._extend_menu(menu))
  File "/snap/remarkable/5/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 524, in _extend_menu
    if not self._enabled:
AttributeError: 'SpellChecker' object has no attribute '_enabled'
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: _ZN6WebKit14WebProcessMainEiPPc
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: _ZN6WebKit18NetworkProcessMainEiPPc
