### ISSUE TITLE
Installer fail

### ISSUE THREAD

**Issue by ANTZ314** [jamiemcg/Remarkable#403]
Attempted various installation methods with .deb file and keep getting the same error:
```
remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
```
New installation Ubuntu 22.04

Please help, I really love 'Remarkable'!

**Comment by piperoc** [comment]
You are in for a ride. I tried a few suggestions but eventually gave up and found another editor.
I started my journey from the following post and then went into a rabbit hole, maybe you will have better luck:
[Issue 400](https://github.com/jamiemcg/Remarkable/issues/400)

**Comment by clarkevans** [comment]
The same issue here.

```
Preparing to unpack .../remarkable_1.87_all.deb ...
Unpacking remarkable (1.87) ...
dpkg: dependency problems prevent configuration of remarkable:
 remarkable depends on gir1.2-gtksource-3.0; however:
  Package gir1.2-gtksource-3.0 is not installed.
 remarkable depends on gir1.2-webkit-3.0; however:
  Package gir1.2-webkit-3.0 is not installed.
 remarkable depends on wkhtmltopdf; however:
  Package wkhtmltopdf is not installed.
```

**Comment by LouieTian0209** [comment]
Same here. This project seems abandoned. Guess we'll have to move onto another markdown editor.

**Comment by davidg-sil** [comment]
For what it's worth: *this* works for me (ububtu 22.04)
```
$ cd ~/src
$ clone https://github.com/jamiemcg/remarkable
$ ln -s ~/src/remarkable/run.sh ~/bin/remarkable
$ cd ~/my/work/directory
$ remarkable file.md
```
(I guess I have the right python libs installed already)
