### ISSUE TITLE
images not included when exporting to pdf

### ISSUE THREAD

**Issue by sjsrey** [jamiemcg/Remarkable#45]
In the preview window the images are rendered correctly, however when exporting to pdf the images are lost.

![screenshot at 2016-08-31 08 50 34](https://cloud.githubusercontent.com/assets/118042/18135907/5e9ab808-6f58-11e6-85f7-54a60a91dcb8.png)

![screenshot at 2016-08-31 08 51 28](https://cloud.githubusercontent.com/assets/118042/18135920/68ecbc84-6f58-11e6-95fb-171b14e0f933.png)

**Comment by jamiemcg** [comment]
Seems to be a bug with relative paths and possibly related to #42 
I'll look into it!

**Comment by skrzepto** [comment]
Also getting the same problem here. Seems also that remarkable doesn't like paths where folders have spaces in them

**Comment by timeraider4u** [comment]
Any news for this bug report?

**Comment by timeraider4u** [comment]
@Alkaid-Benetnash: I have tried your proposed patch, but unfortunately the bug remains. Strange thing is that if I export a styled HTML from remarkable and then convert the file with `wkhtmltopdf my.html out.pdf` I receive a PDF which contains all my images.

**Comment by Alkaid-Benetnash** [comment]
@timeraider4u Hi, May I have your test case? I might make some inconsiderate mistakes.

**Comment by timeraider4u** [comment]
@Alkaid-Benetnash Sorry for my late reply, I have tried it again now. Seems that it worked this time (at least the images were included in the PDF). So maybe it was my fault and the patch was not applied to the correct file. Anyway, I will try it again next week at my workstation at work...

This is my test case: `![firewall-vnc](./images/firewall-vnc.png)`

**Comment by timeraider4u** [comment]
I have tried again to apply your patch and it works for me. Thank you very much for your work! Looking forward to being merged.
