### ISSUE TITLE
custom css never persist in preferences on ubuntu 16

### ISSUE THREAD

**Issue by oDevArc** [jamiemcg/Remarkable#47]
hello

I switch to Ubuntu 16 recently but my custom css is never used by default even if the file in /home/odevarc/.remarkable/remarkable.settings is correctly filled with my custom css 

do you have any ideas ? (I also tried to update the styles.py with no success :-(

thank you for your work and your help

Ode

**Comment by jamiemcg** [comment]
Hi,

When you launch Remarkable it will also revert to the default "GitHub" style. To apply your custom css you have to choose it from the styles menu.

In the future, I will make it so that on launch Remarkable will use the last used style.
