### ISSUE TITLE
Make line numbers less obtrusive

### ISSUE THREAD

**Issue by hugopeek** [jamiemcg/Remarkable#49]
I like the new line numbers feature, but could you make their styling a little less conspicuous? By making them light grey instead of black for example?

Now it's difficult for example to spot rows that start with a number:
![screenshot from 2016-09-06 11 50 47](https://cloud.githubusercontent.com/assets/5436121/18261361/bbde25f6-7429-11e6-95cb-a302a09c3690.png)

Thanks for the update and keep up the good work!

**Comment by bbenoit** [comment]
Agree.
I have no idea if it is easily feasible or not, but adding a visual gutter for those line numbers should do the job.
