### ISSUE TITLE
MathJax flickering

### ISSUE THREAD

**Issue by jamiemcg** [jamiemcg/Remarkable#5]
Flickers due to update on every key press. Add delay or specifically delay MathJax 

[This](https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html) doesn't flicker for example.

**Comment by jamiemcg** [comment]
Will be fixed with #13

**Comment by oersted** [comment]
I can confirm this issue is still present on the latest build. The problem seems to be that every time a new character is inserted the mathjax formulas change font or size (hard to tell) for a subsecond so the whole window moves when it goes back to normal.
