### ISSUE TITLE
Remember last visited folder when opening files

### ISSUE THREAD

**Issue by hugopeek** [jamiemcg/Remarkable#50]
In addition to #40..

**Comment by sergiodlc** [comment]
This probably should be kept the way it is right now. See http://stackoverflow.com/a/14710828 and [Help the user choose a place to put a new file](https://wiki.gnome.org/Initiatives/DocumentCentricGnome/Help%20the%20user%20choose%20a%20place%20to%20put%20a%20new%20file) in the GNOME documentation.

**Comment by harogaston** [comment]
Also auto open last viewed file upon start please!
