### ISSUE TITLE
Shortcut list?

### ISSUE THREAD

**Issue by tleb** [jamiemcg/Remarkable#52]
I haven't found a list of the available of shortcuts, is there one available anywhere? I looked at the code but I haven't found anything. I only know of Ctrl+B and Ctrl+I which I guessed by seeing the video.

I am looking at a shortcut to toggle the live preview (because I have a lot of math in my doc).

If anyone could give me the lines where shortcuts are defined, I could add my own in a fork. Maybe a longer term solution would be a shortcut manager (?).

Thank you for the software, great for note taking ! :)

**Comment by JimH44** [comment]
Yes, a list of shortcut keys would be very helpful, so I would upvote this one if I could.
Of particular value would be Ctrl-F to Find, Ctrl-G to find aGain (with Ctrl-Shift-G to search up again), Ctrl-H to Find and Replace, and Alt-F, Alt-E etc to open the menus.
Shortcut keys are always faster to use than the mouse, and avoid the risk of clicking the adjacent thing by mistake.
I have a spreadsheet of what I see as deficiencies in MarkDown editors for Linux, at
[MarkDown Editor Shortcomings](https://docs.google.com/spreadsheets/d/1Qe6IYOv_wEyc407FilYZFLx4qtI4XPdnuyliqDgU9SU/edit#gid=0)
Anyone with the link can view it and leave comments. It may be that Remarkable has things I would like, but I couldn't find them.
