### ISSUE TITLE
Internal hyperlinks are not preserved when exporting to PDF

### ISSUE THREAD

**Issue by Unknown-404** [jamiemcg/Remarkable#57]
When a file is exported to PDF, internal hyperlinks do not work in the pdf.

**Comment by gbillig** [comment]
+1

**Comment by cipri-tom** [comment]
This is a bug related to the dependency `wkhtmltopdf` under Ubuntu. Because Remarkable uses `pdfkit` to export to PDF, which in turn has this [**warning**](https://github.com/JazzCore/python-pdfkit):

> Version in debian/ubuntu repos have reduced functionality (because it compiled without the wkhtmltopdf QT patches), such as adding outlines, headers, footers, TOC etc. To use this options you should install static binary from [wkhtmltopdf](http://wkhtmltopdf.org/) site or you can use [this script](https://github.com/JazzCore/python-pdfkit/blob/master/travis/before-script.sh).
