### ISSUE TITLE
Package Remarkable in AppImage

### ISSUE THREAD

**Issue by rizaumami** [jamiemcg/Remarkable#60]
Among the now competing portable distribution method ([AppImage](https://github.com/probonopd/AppImages), Snap, and Flatpak), [AppImage](https://github.com/probonopd/AppImages) is the most universal. No need to tied into certain distribution or desktop environment.

Please package Remarkable in AppImage format to ease potensial user.

**Comment by gnacho** [comment]
+1 to Flatpack, which is supposed to have Gnome, Red Hat and other big actors support.
