### ISSUE TITLE
No Response to Night Mode

### ISSUE THREAD

**Issue by gavinfish** [jamiemcg/Remarkable#62]
I use remarkable on Ubuntu 16.04 LTS. When I choose night mode, nothing has changed. Is there anything wrong, or I just miss something?

**Comment by jamiemcg** [comment]
From FAQ:
---
Why doesn't "Night Mode" work?

Availability of night mode is dependent on which Gtk theme you are using. For example, Linux Mint and Ubuntu's default themes do not support dark mode. Gnome's does. Numix is the Gtk theme used in the screenshots and it has a dark mode.

**Comment by zoltanmaric** [comment]
On Ubuntu 16.04, you can install the abovementioned Numix theme as described [here](https://itsfoss.com/install-numix-ubuntu/):

```bash
sudo apt-get install unity-tweak-tool

sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme numix-icon-theme-circle
```

Then open the unity tweak tool, select "Theme" and choose the Numix theme. Night mode should now work.
![Unity Tweak Tool Screenshot](https://itsfoss.com/wp-content/uploads/2013/11/Unity_tweak_tool_1.jpeg)
