### ISSUE TITLE
text window takes too long to respond the keyword click

### ISSUE THREAD

**Issue by tilneyyang** [jamiemcg/Remarkable#63]
After installing the .deb package(version 1.87) from official site on Ubuntu 12.04,  when I try to type something, the text window takes too long to respond.

No warnings or exception stacktraces when I run remarkable from command line.

**Comment by psicofrenia** [comment]
I have exactly the same problem. This happens with _Linux Mint 17 & 18_.

I can't also get any warnings, only a very painful delay.

**Comment by psicofrenia** [comment]
I believe this is actually a problem with the live preview. If you disable it, this problem disappears.
