### ISSUE TITLE
Add support to specify syntax highlighting language

### ISSUE THREAD

**Issue by pavlin-policar** [jamiemcg/Remarkable#64]
It seems that programming languages are detected automatically and there's no way to change which one it chooses.

It would be really convenient if the program supported what Github does where you can specify the language like this:

```
    ```text
    ...
    ```
```

Trying to make a simple code diagram like this

```
    ```
    RegressionTree <- Tree -> ClassificationTree
    ```
```

changes the highlighting to something strange, when all I want is plain old text.

**Comment by sergiodlc** [comment]
The syntax in Remarkable is a little different from the one GitHub uses. Try this instead:

~~~python
def my_func():
    pass
~~~

Actually, the very same syntax that GitHub uses works just fine.

More here: https://support.codebasehq.com/articles/tips-tricks/syntax-highlighting-in-markdown

**Comment by pavlin-policar** [comment]
My bad, it seems that it just doesn't have a plain `text` setting that overrides highlighting. Thanks!
