### ISSUE TITLE
Unexpected ordered list numbering

### ISSUE THREAD

**Issue by qwelnor** [jamiemcg/Remarkable#68]
Hello,
I found Remarkable very useful but it does not follow ordering numbers as entered (sample attached).

[test.txt](https://github.com/jamiemcg/Remarkable/files/535985/test.txt)

**Comment by sergiodlc** [comment]
I think your issues are with Markdown itself. Try this instead:
~~~~
1. Lorem ipsum
2. Lorem ipsum
3. Lorem ipsum
    ```
    code snippet
    ```
4. Lorem ipsum
5. Lorem ipsum
~~~~

Note the indentation in the block of code. Hope this helps.

**Comment by qwelnor** [comment]
@sergiodlc thanks for tip but it only works with one liners. Multiple lines are rendered as single line.
When I try the same text (original or your tip) with atom or haroopad editors it is rendered as expected and with multiple lines are rendered as multiple lines.

**Comment by sergiodlc** [comment]
@qwelnor You are right, it does collapse multiple lines into one. I tried several variations and the one so far that gets the job done is like this:
```
1. Lorem ipsum
2. Lorem ipsum
3. Lorem ipsum

        code snippet
        with another line
        ... and yet another one
        and still another one to be safe

4. Lorem ipsum
5. Lorem ipsum
```
So it removes the backticks and indents the code part by another 4 spaces. This, however, doesn't allow me to neither select the language for code highlighting nor remove the automatic code highlighting.

It does look like a legitimate issue. If you are interesting in working on a fix for this, I can give you some clues on how to go about it.

**Comment by jamiemcg** [comment]
This is an issue with [Python Markdown](https://pypi.python.org/pypi/Markdown)
