### ISSUE TITLE
Settings not persistent after updating to Latest Version 1.87

### ISSUE THREAD

**Issue by studenton** [jamiemcg/Remarkable#72]
I manually download the latest deb file and installed it over the previous installation. Now, when I change the options like **style** and **view** from the menu, it gets reset when I open another markdown file. 

`Steps to reproduce:`
- Open any markdown file using Remarkable
- Change the default option from menu
- Close the markdown file
- Re-open it

System used: _Linux Mint 17.1 on Dell Inspiron_

**Comment by jamiemcg** [comment]
Cannot reproduce this issue. Tested on Ubunut 16.10 & Fedora 25.

**Comment by studenton** [comment]
@jamiemcg It was fixed due to recent updates. Thanks.
