### ISSUE TITLE
Cannot change syntax highlighting of the editable area under Ubuntu 16.04

### ISSUE THREAD

**Issue by RobertoPrevato** [jamiemcg/Remarkable#75]
Styles seem to not be applied on the editor panel, under Ubuntu 16.04. The background of the editable area is always gray and some elements are really hard to read (e.g. texts inside square brackets). Switching the night mode on/off, doesn't produce any result on the interface. I have Unity Tweak tool installed and I am using a custom theme (Arc), but this doesn't seem to be the cause because the same issue persists when using default Ubuntu themes (for example, Ambiance).

If possible, could you please indicate a configuration file that can be edited to change the colors of the editable area?

![screenshot from 2016-10-25 22-05-26](https://cloud.githubusercontent.com/assets/2576032/19704760/4b400e70-9b09-11e6-814a-621ec8f062d2.png)

**Comment by emodric** [comment]
Happens on Ubuntu 16.10 too.

Any fix?

**Comment by balaianu** [comment]
+1 on Ubuntu 15.10

**Comment by RobertoPrevato** [comment]
Recommendation for people looking at this in the future: you can use Visual Studio Code. It has great preview of markdown files.
