### ISSUE TITLE
Glade files

### ISSUE THREAD

**Issue by paulwuertz** [jamiemcg/Remarkable#83]
It seems you wrote the GUI with glade, but there are no .glade  files. Could you add them to the repo? I'd like to add some function, but rather not by hand, if differently intended ;)

**Comment by gurditsbedi** [comment]
Many times when developing software. The glade file(".glade") have a different extension. I have seen ".ui" most of the time.
If you are on a linux/mac run this command in the git folder of this application you will get the location of the required files.
`find . -type f | while read i ; do mimetype $i; done | grep x-designer`

**Comment by jacmoe** [comment]
The Glade files seems to be in the 'data' directory @paulwuertz
