### ISSUE TITLE
[feature request] (Auto) refresh

### ISSUE THREAD

**Issue by johnnybaloney** [jamiemcg/Remarkable#84]
I tend to edit markdown files in a separate editor or view files that are under source code and then update the code or change branches etc. When the file changes I have to close and reopen Remarkable. Opening the file again with `ctrl+o` results in a new editor window so it doesn't work as a 'workaround'.

It would be nice if there was a 'Refresh' feature available for such cases with a big menu button and the usual F5 keyboard shortcut.

An optional 'Auto Refresh' feature would be a great addition too.

**Comment by jamiemcg** [comment]
Will be implemented as in #97
