### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-24: ordinal not in range(128)

### ISSUE THREAD

**Issue by DFooz** [jamiemcg/Remarkable#85]
When I try to input cyrillic characters and try to save a file, I get an error and the file doesn't save
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/remarkable/RemarkableWindow.py", line 419, in on_menuitem_save_activate
>     self.save(self)
>   File "/usr/lib/python3.5/site-packages/remarkable/RemarkableWindow.py", line 428, in save
>     file.write(text)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-24: ordinal not in range(128)
> 

**input text:**

> $dfadaf$
> $$
> dfsg
> $$
> 
> апвп

ReMarkable is from AUR:

https://aur.archlinux.org/packages/remarkable/

**Comment by sergiodlc** [comment]
Hey, @DFooz. I tried to reproduce your issue to no avail. I'm using Arch Linux, also with Remarkable from the AUR. I can save and reopen files with Cyrillic characters with no issues.

What's the output for the **locale** command in your system? Mine is:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
I suspect that what might be happening is that your locale is set to ASCII and that's why it tries to save it with that encoding.

**Comment by DFooz** [comment]
> $ locale
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> LANG=cv_RU.UTF-8
> LC_CTYPE="cv_RU.UTF-8"
> LC_NUMERIC="cv_RU.UTF-8"
> LC_TIME="cv_RU.UTF-8"
> LC_COLLATE=en_US.UTF-8
> LC_MONETARY="cv_RU.UTF-8"
> LC_MESSAGES="cv_RU.UTF-8"
> LC_PAPER="cv_RU.UTF-8"
> LC_NAME="cv_RU.UTF-8"
> LC_ADDRESS="cv_RU.UTF-8"
> LC_TELEPHONE="cv_RU.UTF-8"
> LC_MEASUREMENT="cv_RU.UTF-8"
> LC_IDENTIFICATION="cv_RU.UTF-8"
> LC_ALL=
>
