### ISSUE TITLE
Unlisted dependency

### ISSUE THREAD

**Issue by galvao** [jamiemcg/Remarkable#88]
After installing the dependencies remarkable complains about (python3-markdown and wkhtmltopdf) this is the output when I try to run ir:

```bash
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

Had to also dnf install gtkviewsource3 to make it work.

**Comment by jimkp** [comment]
Thanks for reporting this. Not sure what distro and version you are using but for Fedora 25 the required package is gtksourceview3 so dnf install gtksourceview3 is the command.

**Comment by galvao** [comment]
Yes, you're correct: The package name is gtksourceview3 and yes, Fedora 25 over here. 

Thank you.

**Comment by kknundy** [comment]
Remarkable fails to open on openSUSE Tumbleweed as well. 
After installing `libwebkitgtk3-devel`, `python3-Markdown`, and `ghc-gtksourceview3`, the error remains.

```python
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

The `python-gtksourceview` package in openSUSE repos corresponds to gtksourceview2, and installing `libgtksourceview-4-0` and `libgtksourceview-3_0-1` does not seem to help either.

**Comment by shrinidhi111** [comment]
> Remarkable fails to open on openSUSE Tumbleweed as well.
> After installing `libwebkitgtk3-devel`, `python3-Markdown`, and `ghc-gtksourceview3`, the error remains.
> 
> ```python
> Traceback (most recent call last):
>   File "/usr/bin/remarkable", line 65, in <module>
>     import remarkable
>   File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
>     from remarkable import RemarkableWindow
>   File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 26, in <module>
>     gi.require_version('GtkSource', '3.0')
>   File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 118, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace GtkSource not available
> ```
> 
> The `python-gtksourceview` package in openSUSE repos corresponds to gtksourceview2, and installing `libgtksourceview-4-0` and `libgtksourceview-3_0-1` does not seem to help either.

I would encourage you to check your path again. It works for me. Ensure you install libgtksourceview-3.0-dev (or the  corresponding name)

**Comment by ployt0** [comment]
Well, I'll be!

Installed all the other libgtksourceview-x.x0 first and none worked (libgtksourceview-4-dev took 250Mb on disk, libgtksourceview-3.0-1)

Only libgtksourceview-3.0-dev would get this to work. Which is strange since it worked straight off (older download binary, plus current source with only minor script tweaks) on my other laptop, where the 75kb download really sold it to me.

The comments at https://askubuntu.com/q/1154986 were quire interesting.

Overcoming this is a huge barrier to attracting new devs. I'll call it a night now but am still keen to clean up all those `sys.path.append`  abominations.

**Comment by rthickling** [comment]
After some effort I have Remarkable working on an Ubuntu 19.10 system.  I've listed the packages I needed [here](https://github.com/jamiemcg/Remarkable/issues/333#issuecomment-596198922).
