### ISSUE TITLE
Export HTML: No charset set

### ISSUE THREAD

**Issue by thtomate** [jamiemcg/Remarkable#89]
The file exported with the Export HTML feature are Unicode, but browsers (Firefox and Vivaldi tested) use other codepages by default. So there aren't proper umlauts etc. 😭

**Comment by glithc** [comment]
The same problem occurs when exporting to pdf.

![screenshot from 2016-12-29 22-37-06](https://cloud.githubusercontent.com/assets/10927853/21555321/69640e2e-ce17-11e6-80b3-1a7fec513086.png)
