### ISSUE TITLE
Installation from source failed

### ISSUE THREAD

**Issue by elija** [jamiemcg/Remarkable#92]
OS: openSUSE Leap 42.2

    python3 setup.py build
        File "setup.py", line 57
        except (OSError, IOError), e:
                        ^
    SyntaxError: invalid syntax

**Comment by jluttine** [comment]
If `setup.py` is not supported (see https://github.com/jamiemcg/Remarkable/issues/67#issuecomment-254041520), could you describe some other method of installing from source? For instance, how do you create the binary .deb package from source? Although I'd definitely prefer the standard `setup.py` which enables using `pip` for installing.

**Comment by jamiemcg** [comment]
See #67 .
Script to produce binary package will be uploaded.
Binary packages are used to count downloads.
