### ISSUE TITLE
Can one create a list (bullets, numbered or not) inside a table.

### ISSUE THREAD

**Issue by ram1123** [jamiemcg/Remarkable#96]
Hi,

Can one create a list (bullets, numbered or not) inside a markdown table?

One of example I am attaching in this post.

![1oi78](https://cloud.githubusercontent.com/assets/5220316/21889782/9f71df30-d8f0-11e6-8582-085c70fc16a4.png)

**Comment by jamiemcg** [comment]
No, this is not possible in markdown.
